"""versioned agent runtime

Revision ID: 0dbbf7d04806
Revises: a2f100000011
Create Date: 2026-07-19 04:06:20.891968
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0dbbf7d04806"
down_revision: str | Sequence[str] | None = "a2f100000011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_artifacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("logical_id", sa.String(length=150), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_path", sa.String(length=500), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "kind IN ('prompt', 'schema', 'model_profile', 'toolset')", name=op.f("ck_agent_artifacts_kind_values")
        ),
        sa.CheckConstraint("sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_agent_artifacts_sha256_format")),
        sa.CheckConstraint("version > 0", name=op.f("ck_agent_artifacts_positive_version")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_artifacts")),
        sa.UniqueConstraint("logical_id", "kind", "sha256", name="uq_agent_artifacts_logical_kind_hash"),
        sa.UniqueConstraint("logical_id", "kind", "version", name="uq_agent_artifacts_logical_kind_version"),
    )
    op.create_table(
        "agent_capabilities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("logical_id", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("active_version_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_capabilities")),
        sa.UniqueConstraint("logical_id", name=op.f("uq_agent_capabilities_logical_id")),
    )
    op.create_index(
        op.f("ix_agent_capabilities_active_version_id"), "agent_capabilities", ["active_version_id"], unique=False
    )
    op.create_table(
        "agent_eval_datasets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("logical_id", sa.String(length=150), nullable=False),
        sa.Column("capability_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_agent_eval_datasets_sha256_format")),
        sa.ForeignKeyConstraint(
            ["capability_id"],
            ["agent_capabilities.id"],
            name=op.f("fk_agent_eval_datasets_capability_id_agent_capabilities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_eval_datasets")),
        sa.UniqueConstraint("logical_id", "version", name="uq_agent_eval_datasets_logical_version"),
    )
    op.create_table(
        "agent_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("capability_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("prompt_artifact_id", sa.Uuid(), nullable=False),
        sa.Column("schema_artifact_id", sa.Uuid(), nullable=False),
        sa.Column("model_artifact_id", sa.Uuid(), nullable=False),
        sa.Column("toolset_artifact_id", sa.Uuid(), nullable=False),
        sa.Column("budgets", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("policies", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft', 'candidate', 'active', 'retired')", name=op.f("ck_agent_versions_status_values")
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_agent_versions_positive_version")),
        sa.ForeignKeyConstraint(
            ["capability_id"],
            ["agent_capabilities.id"],
            name=op.f("fk_agent_versions_capability_id_agent_capabilities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["model_artifact_id"],
            ["agent_artifacts.id"],
            name=op.f("fk_agent_versions_model_artifact_id_agent_artifacts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["prompt_artifact_id"],
            ["agent_artifacts.id"],
            name=op.f("fk_agent_versions_prompt_artifact_id_agent_artifacts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["schema_artifact_id"],
            ["agent_artifacts.id"],
            name=op.f("fk_agent_versions_schema_artifact_id_agent_artifacts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["toolset_artifact_id"],
            ["agent_artifacts.id"],
            name=op.f("fk_agent_versions_toolset_artifact_id_agent_artifacts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_versions")),
        sa.UniqueConstraint("capability_id", "version", name="uq_agent_versions_capability_version"),
    )
    op.create_index(op.f("ix_agent_versions_capability_id"), "agent_versions", ["capability_id"], unique=False)
    op.create_table(
        "agent_eval_cases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("case_key", sa.String(length=150), nullable=False),
        sa.Column("input_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expected_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["agent_eval_datasets.id"],
            name=op.f("fk_agent_eval_cases_dataset_id_agent_eval_datasets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_eval_cases")),
        sa.UniqueConstraint("dataset_id", "case_key", name="uq_agent_eval_cases_dataset_key"),
    )
    op.create_index(op.f("ix_agent_eval_cases_dataset_id"), "agent_eval_cases", ["dataset_id"], unique=False)
    op.create_table(
        "agent_eval_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("baseline_version_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_version_id", sa.Uuid(), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("thresholds", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('running', 'passed', 'failed')", name=op.f("ck_agent_eval_runs_status_values")),
        sa.ForeignKeyConstraint(
            ["baseline_version_id"],
            ["agent_versions.id"],
            name=op.f("fk_agent_eval_runs_baseline_version_id_agent_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["candidate_version_id"],
            ["agent_versions.id"],
            name=op.f("fk_agent_eval_runs_candidate_version_id_agent_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["agent_eval_datasets.id"],
            name=op.f("fk_agent_eval_runs_dataset_id_agent_eval_datasets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_eval_runs")),
    )
    op.create_table(
        "agent_promotions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("capability_id", sa.Uuid(), nullable=False),
        sa.Column("from_version_id", sa.Uuid(), nullable=True),
        sa.Column("to_version_id", sa.Uuid(), nullable=False),
        sa.Column("eval_run_id", sa.Uuid(), nullable=False),
        sa.Column("override_reason", sa.Text(), nullable=True),
        sa.Column("override_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("promoted_by", sa.String(length=255), nullable=False),
        sa.Column("promoted_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["capability_id"],
            ["agent_capabilities.id"],
            name=op.f("fk_agent_promotions_capability_id_agent_capabilities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["eval_run_id"],
            ["agent_eval_runs.id"],
            name=op.f("fk_agent_promotions_eval_run_id_agent_eval_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["from_version_id"],
            ["agent_versions.id"],
            name=op.f("fk_agent_promotions_from_version_id_agent_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["to_version_id"],
            ["agent_versions.id"],
            name=op.f("fk_agent_promotions_to_version_id_agent_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_promotions")),
    )
    op.create_index(op.f("ix_agent_promotions_capability_id"), "agent_promotions", ["capability_id"], unique=False)
    op.create_table(
        "agent_runtime_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("capability_id", sa.Uuid(), nullable=False),
        sa.Column("agent_version_id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=True),
        sa.Column("workflow_id", sa.String(length=255), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("input_sha256", sa.String(length=64), nullable=False),
        sa.Column("input_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("output_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("data_as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("knowledge_cutoff", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("provider_run_id", sa.String(length=255), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=16, scale=8), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("evidence_coverage", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("input_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_agent_runtime_runs_sha256_format")),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'awaiting_approval', 'succeeded', 'failed', 'cancelled', 'expired')",
            name=op.f("ck_agent_runtime_runs_status_values"),
        ),
        sa.CheckConstraint(
            "evidence_coverage IS NULL OR evidence_coverage BETWEEN 0 AND 1",
            name=op.f("ck_agent_runtime_runs_coverage_range"),
        ),
        sa.CheckConstraint("knowledge_cutoff <= data_as_of", name=op.f("ck_agent_runtime_runs_valid_temporal_cutoff")),
        sa.CheckConstraint(
            "prompt_tokens >= 0 AND completion_tokens >= 0 AND cost_usd >= 0",
            name=op.f("ck_agent_runtime_runs_nonnegative_usage"),
        ),
        sa.ForeignKeyConstraint(
            ["agent_version_id"],
            ["agent_versions.id"],
            name=op.f("fk_agent_runtime_runs_agent_version_id_agent_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["capability_id"],
            ["agent_capabilities.id"],
            name=op.f("fk_agent_runtime_runs_capability_id_agent_capabilities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["research_cases.id"],
            name=op.f("fk_agent_runtime_runs_case_id_research_cases"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runtime_runs")),
    )
    op.create_index(op.f("ix_agent_runtime_runs_case_id"), "agent_runtime_runs", ["case_id"], unique=False)
    op.create_index(op.f("ix_agent_runtime_runs_status"), "agent_runtime_runs", ["status"], unique=False)
    op.create_index(op.f("ix_agent_runtime_runs_trace_id"), "agent_runtime_runs", ["trace_id"], unique=False)
    op.create_index(op.f("ix_agent_runtime_runs_workflow_id"), "agent_runtime_runs", ["workflow_id"], unique=False)
    op.create_table(
        "agent_runtime_tool_calls",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("tool_name", sa.String(length=100), nullable=False),
        sa.Column("tool_version", sa.Integer(), nullable=False),
        sa.Column("arguments_sha256", sa.String(length=64), nullable=False),
        sa.Column("sanitized_arguments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=16, scale=8), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "arguments_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_agent_runtime_tool_calls_sha256_format")
        ),
        sa.CheckConstraint(
            "status IN ('requested', 'approved', 'succeeded', 'failed', 'blocked')",
            name=op.f("ck_agent_runtime_tool_calls_status_values"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runtime_runs.id"],
            name=op.f("fk_agent_runtime_tool_calls_run_id_agent_runtime_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runtime_tool_calls")),
    )
    op.create_index(op.f("ix_agent_runtime_tool_calls_run_id"), "agent_runtime_tool_calls", ["run_id"], unique=False)
    op.create_table(
        "agent_approval_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("tool_call_id", sa.Uuid(), nullable=False),
        sa.Column("scope", sa.String(length=100), nullable=False),
        sa.Column("impact", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("requested_by", sa.String(length=255), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("decided_by", sa.String(length=255), nullable=True),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected', 'expired', 'cancelled')",
            name=op.f("ck_agent_approval_requests_status_values"),
        ),
        sa.CheckConstraint("expires_at > requested_at", name=op.f("ck_agent_approval_requests_valid_expiry")),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runtime_runs.id"],
            name=op.f("fk_agent_approval_requests_run_id_agent_runtime_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tool_call_id"],
            ["agent_runtime_tool_calls.id"],
            name=op.f("fk_agent_approval_requests_tool_call_id_agent_runtime_tool_calls"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_approval_requests")),
        sa.UniqueConstraint("tool_call_id", name=op.f("uq_agent_approval_requests_tool_call_id")),
    )
    op.create_index(op.f("ix_agent_approval_requests_run_id"), "agent_approval_requests", ["run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_approval_requests_run_id"), table_name="agent_approval_requests")
    op.drop_table("agent_approval_requests")
    op.drop_index(op.f("ix_agent_runtime_tool_calls_run_id"), table_name="agent_runtime_tool_calls")
    op.drop_table("agent_runtime_tool_calls")
    op.drop_index(op.f("ix_agent_runtime_runs_workflow_id"), table_name="agent_runtime_runs")
    op.drop_index(op.f("ix_agent_runtime_runs_trace_id"), table_name="agent_runtime_runs")
    op.drop_index(op.f("ix_agent_runtime_runs_status"), table_name="agent_runtime_runs")
    op.drop_index(op.f("ix_agent_runtime_runs_case_id"), table_name="agent_runtime_runs")
    op.drop_table("agent_runtime_runs")
    op.drop_index(op.f("ix_agent_promotions_capability_id"), table_name="agent_promotions")
    op.drop_table("agent_promotions")
    op.drop_table("agent_eval_runs")
    op.drop_index(op.f("ix_agent_eval_cases_dataset_id"), table_name="agent_eval_cases")
    op.drop_table("agent_eval_cases")
    op.drop_index(op.f("ix_agent_versions_capability_id"), table_name="agent_versions")
    op.drop_table("agent_versions")
    op.drop_table("agent_eval_datasets")
    op.drop_index(op.f("ix_agent_capabilities_active_version_id"), table_name="agent_capabilities")
    op.drop_table("agent_capabilities")
    op.drop_table("agent_artifacts")
    # ### end Alembic commands ###
