"""institutional identity portfolios risk and backtest

Revision ID: 2a3d784c8e65
Revises: 0dbbf7d04806
Create Date: 2026-07-19 04:29:34.319696
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "2a3d784c8e65"
down_revision: str | Sequence[str] | None = "0dbbf7d04806"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("slug", name=op.f("uq_organizations_slug")),
    )
    op.create_table(
        "permissions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissions")),
        sa.UniqueConstraint("name", name=op.f("uq_permissions_name")),
    )
    op.create_table(
        "stress_scenarios",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("logical_id", sa.String(length=100), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("shocks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.CheckConstraint("content_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_stress_scenarios_sha256_format")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stress_scenarios")),
        sa.UniqueConstraint("logical_id", "version", name="uq_stress_scenarios_logical_version"),
    )
    op.create_table(
        "user_identities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("oidc_issuer", sa.String(length=500), nullable=False),
        sa.Column("oidc_subject", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_identities")),
        sa.UniqueConstraint("oidc_issuer", "oidc_subject", name="uq_user_identities_issuer_subject"),
    )
    op.create_table(
        "backtest_configs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("strategy_name", sa.String(length=200), nullable=False),
        sa.Column("universe_definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("benchmark_index_id", sa.Uuid(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("signal_delay_sessions", sa.Integer(), nullable=False),
        sa.Column("costs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("taxes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("config_sha256", sa.String(length=64), nullable=False),
        sa.CheckConstraint("config_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_backtest_configs_sha256_format")),
        sa.CheckConstraint("end_date >= start_date", name=op.f("ck_backtest_configs_valid_dates")),
        sa.CheckConstraint("signal_delay_sessions >= 1", name=op.f("ck_backtest_configs_positive_signal_delay")),
        sa.ForeignKeyConstraint(
            ["benchmark_index_id"],
            ["market_indices.id"],
            name=op.f("fk_backtest_configs_benchmark_index_id_market_indices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_backtest_configs_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backtest_configs")),
        sa.UniqueConstraint("config_sha256", name=op.f("uq_backtest_configs_config_sha256")),
    )
    op.create_index(op.f("ix_backtest_configs_organization_id"), "backtest_configs", ["organization_id"], unique=False)
    op.create_table(
        "organization_memberships",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_organization_memberships_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_identities.id"],
            name=op.f("fk_organization_memberships_user_id_user_identities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_memberships")),
        sa.UniqueConstraint("organization_id", "user_id", name="uq_organization_memberships_org_user"),
    )
    op.create_index(
        op.f("ix_organization_memberships_organization_id"),
        "organization_memberships",
        ["organization_id"],
        unique=False,
    )
    op.create_index(op.f("ix_organization_memberships_user_id"), "organization_memberships", ["user_id"], unique=False)
    op.create_table(
        "roles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_roles_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("organization_id", "name", name="uq_roles_organization_name"),
    )
    op.create_table(
        "service_identities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("logical_id", sa.String(length=150), nullable=False),
        sa.Column("identity_type", sa.String(length=30), nullable=False),
        sa.Column("capability", sa.String(length=100), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "identity_type IN ('agent', 'worker', 'service')", name=op.f("ck_service_identities_identity_type_values")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_service_identities_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_identities")),
        sa.UniqueConstraint("organization_id", "logical_id", name="uq_service_identities_organization_logical"),
    )
    op.create_index(
        op.f("ix_service_identities_organization_id"), "service_identities", ["organization_id"], unique=False
    )
    op.create_table(
        "strategy_mandates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("logical_id", sa.String(length=100), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("strategy_type", sa.String(length=50), nullable=False),
        sa.Column("universe_definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("benchmark_index_id", sa.Uuid(), nullable=False),
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column("investment_horizon_days", sa.Integer(), nullable=False),
        sa.Column("rebalance_policy", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("risk_budget", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("target_volatility", sa.Numeric(precision=8, scale=6), nullable=True),
        sa.Column("max_drawdown", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("concentration_limits", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("factor_limits", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("liquidity_policy", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("min_cash_weight", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("max_cash_weight", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("max_turnover", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("exclusions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cost_policy", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tax_policy", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("approval_policy", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("base_currency ~ '^[A-Z]{3}$'", name=op.f("ck_strategy_mandates_currency_format")),
        sa.CheckConstraint("content_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_strategy_mandates_sha256_format")),
        sa.CheckConstraint("status IN ('draft', 'active', 'retired')", name=op.f("ck_strategy_mandates_status_values")),
        sa.CheckConstraint("investment_horizon_days > 0", name=op.f("ck_strategy_mandates_positive_horizon")),
        sa.CheckConstraint("max_drawdown BETWEEN 0 AND 1", name=op.f("ck_strategy_mandates_drawdown_range")),
        sa.CheckConstraint("max_turnover BETWEEN 0 AND 2", name=op.f("ck_strategy_mandates_turnover_range")),
        sa.CheckConstraint(
            "min_cash_weight BETWEEN 0 AND 1 AND max_cash_weight BETWEEN min_cash_weight AND 1",
            name=op.f("ck_strategy_mandates_cash_range"),
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_strategy_mandates_positive_version")),
        sa.ForeignKeyConstraint(
            ["benchmark_index_id"],
            ["market_indices.id"],
            name=op.f("fk_strategy_mandates_benchmark_index_id_market_indices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_strategy_mandates_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strategy_mandates")),
        sa.UniqueConstraint(
            "organization_id", "logical_id", "version", name="uq_strategy_mandates_org_logical_version"
        ),
    )
    op.create_index(
        op.f("ix_strategy_mandates_organization_id"), "strategy_mandates", ["organization_id"], unique=False
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_teams_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teams")),
        sa.UniqueConstraint("organization_id", "slug", name="uq_teams_organization_slug"),
    )
    op.create_index(op.f("ix_teams_organization_id"), "teams", ["organization_id"], unique=False)
    op.create_table(
        "institutional_backtest_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("config_id", sa.Uuid(), nullable=False),
        sa.Column("code_version", sa.String(length=100), nullable=False),
        sa.Column("data_snapshot_sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("result_sha256", sa.String(length=64), nullable=True),
        sa.Column("results", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "data_snapshot_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_institutional_backtest_runs_data_hash_format")
        ),
        sa.CheckConstraint(
            "result_sha256 IS NULL OR result_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_institutional_backtest_runs_result_hash_format"),
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')",
            name=op.f("ck_institutional_backtest_runs_status_values"),
        ),
        sa.ForeignKeyConstraint(
            ["config_id"],
            ["backtest_configs.id"],
            name=op.f("fk_institutional_backtest_runs_config_id_backtest_configs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_institutional_backtest_runs")),
        sa.UniqueConstraint(
            "config_id", "code_version", "data_snapshot_sha256", name="uq_backtest_runs_reproducible_input"
        ),
    )
    op.create_index(
        op.f("ix_institutional_backtest_runs_config_id"), "institutional_backtest_runs", ["config_id"], unique=False
    )
    op.create_table(
        "institutional_risk_policies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("mandate_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("methodology_version", sa.String(length=100), nullable=False),
        sa.Column("limits", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "content_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_institutional_risk_policies_sha256_format")
        ),
        sa.ForeignKeyConstraint(
            ["mandate_id"],
            ["strategy_mandates.id"],
            name=op.f("fk_institutional_risk_policies_mandate_id_strategy_mandates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_institutional_risk_policies")),
        sa.UniqueConstraint("mandate_id", "version", name="uq_institutional_risk_policies_mandate_version"),
    )
    op.create_index(
        op.f("ix_institutional_risk_policies_mandate_id"), "institutional_risk_policies", ["mandate_id"], unique=False
    )
    op.create_table(
        "membership_roles",
        sa.Column("membership_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["membership_id"],
            ["organization_memberships.id"],
            name=op.f("fk_membership_roles_membership_id_organization_memberships"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_membership_roles_role_id_roles"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("membership_id", "role_id", name=op.f("pk_membership_roles")),
    )
    op.create_table(
        "model_portfolios",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("owner_team_id", sa.Uuid(), nullable=False),
        sa.Column("mandate_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.Column("environment", sa.String(length=10), nullable=False),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("environment IN ('paper', 'live')", name=op.f("ck_model_portfolios_environment_values")),
        sa.CheckConstraint(
            "state IN ('draft', 'researching', 'simulated', 'committee_review', 'approved', "
            "'paper_live', 'eligible_for_live', 'live', 'suspended', 'archived')",
            name=op.f("ck_model_portfolios_state_values"),
        ),
        sa.ForeignKeyConstraint(
            ["mandate_id"],
            ["strategy_mandates.id"],
            name=op.f("fk_model_portfolios_mandate_id_strategy_mandates"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_model_portfolios_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_team_id"], ["teams.id"], name=op.f("fk_model_portfolios_owner_team_id_teams"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_portfolios")),
        sa.UniqueConstraint("organization_id", "name", name="uq_model_portfolios_organization_name"),
    )
    op.create_index(op.f("ix_model_portfolios_organization_id"), "model_portfolios", ["organization_id"], unique=False)
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("permission_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name=op.f("fk_role_permissions_permission_id_permissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_role_permissions_role_id_roles"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id", name=op.f("pk_role_permissions")),
    )
    op.create_table(
        "team_memberships",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("organization_membership_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_membership_id"],
            ["organization_memberships.id"],
            name=op.f("fk_team_memberships_organization_membership_id_organization_memberships"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_team_memberships_team_id_teams"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("team_id", "organization_membership_id", name=op.f("pk_team_memberships")),
    )
    op.create_table(
        "institutional_portfolio_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("portfolio_id", sa.Uuid(), nullable=False),
        sa.Column("mandate_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("input_snapshot_sha256", sa.String(length=64), nullable=False),
        sa.Column("weights_sha256", sa.String(length=64), nullable=False),
        sa.Column("approved_weights", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("proposal", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("decision", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("approved_by", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "input_snapshot_sha256 ~ '^[0-9a-f]{64}$' AND weights_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_institutional_portfolio_versions_hash_format"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'proposed', 'approved', 'rejected', 'superseded')",
            name=op.f("ck_institutional_portfolio_versions_status_values"),
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_institutional_portfolio_versions_positive_version")),
        sa.ForeignKeyConstraint(
            ["mandate_id"],
            ["strategy_mandates.id"],
            name=op.f("fk_institutional_portfolio_versions_mandate_id_strategy_mandates"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["model_portfolios.id"],
            name=op.f("fk_institutional_portfolio_versions_portfolio_id_model_portfolios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_institutional_portfolio_versions")),
        sa.UniqueConstraint("portfolio_id", "version", name="uq_institutional_portfolio_versions_portfolio_version"),
    )
    op.create_index(
        op.f("ix_institutional_portfolio_versions_portfolio_id"),
        "institutional_portfolio_versions",
        ["portfolio_id"],
        unique=False,
    )
    op.create_table(
        "optimization_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("portfolio_id", sa.Uuid(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("input_sha256", sa.String(length=64), nullable=False),
        sa.Column("solver", sa.String(length=50), nullable=False),
        sa.Column("solver_version", sa.String(length=50), nullable=False),
        sa.Column("tolerances", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("weights", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("trades", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("slacks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("diagnostics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("input_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_optimization_runs_sha256_format")),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["model_portfolios.id"],
            name=op.f("fk_optimization_runs_portfolio_id_model_portfolios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_optimization_runs")),
        sa.UniqueConstraint("portfolio_id", "as_of", "input_sha256", name="uq_optimization_runs_portfolio_asof_input"),
    )
    op.create_index(op.f("ix_optimization_runs_portfolio_id"), "optimization_runs", ["portfolio_id"], unique=False)
    op.create_table(
        "cash_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("portfolio_version_id", sa.Uuid(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("amount", sa.Numeric(precision=28, scale=8), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["portfolio_version_id"],
            ["institutional_portfolio_versions.id"],
            name=op.f("fk_cash_snapshots_portfolio_version_id_institutional_portfolio_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cash_snapshots")),
        sa.UniqueConstraint("portfolio_version_id", "currency", name="uq_cash_snapshots_version_currency"),
    )
    op.create_index(
        op.f("ix_cash_snapshots_portfolio_version_id"), "cash_snapshots", ["portfolio_version_id"], unique=False
    )
    op.create_table(
        "institutional_risk_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("portfolio_version_id", sa.Uuid(), nullable=False),
        sa.Column("risk_policy_id", sa.Uuid(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("input_sha256", sa.String(length=64), nullable=False),
        sa.Column("exposures", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("concentration", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("liquidity", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("volatility", sa.Numeric(precision=10, scale=8), nullable=True),
        sa.Column("drawdown", sa.Numeric(precision=10, scale=8), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["portfolio_version_id"],
            ["institutional_portfolio_versions.id"],
            name=op.f("fk_institutional_risk_snapshots_portfolio_version_id_institutional_portfolio_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["risk_policy_id"],
            ["institutional_risk_policies.id"],
            name=op.f("fk_institutional_risk_snapshots_risk_policy_id_institutional_risk_policies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_institutional_risk_snapshots")),
        sa.UniqueConstraint(
            "portfolio_version_id", "risk_policy_id", "as_of", name="uq_risk_snapshots_version_policy_asof"
        ),
    )
    op.create_index(
        op.f("ix_institutional_risk_snapshots_portfolio_version_id"),
        "institutional_risk_snapshots",
        ["portfolio_version_id"],
        unique=False,
    )
    op.create_table(
        "nav_publications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("portfolio_id", sa.Uuid(), nullable=False),
        sa.Column("portfolio_version_id", sa.Uuid(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("methodology_version", sa.String(length=100), nullable=False),
        sa.Column("input_sha256", sa.String(length=64), nullable=False),
        sa.Column("cash_value", sa.Numeric(precision=28, scale=8), nullable=False),
        sa.Column("positions_value", sa.Numeric(precision=28, scale=8), nullable=False),
        sa.Column("fees_value", sa.Numeric(precision=28, scale=8), nullable=False),
        sa.Column("taxes_value", sa.Numeric(precision=28, scale=8), nullable=False),
        sa.Column("nav", sa.Numeric(precision=28, scale=8), nullable=False),
        sa.Column("benchmark_value", sa.Numeric(precision=28, scale=8), nullable=True),
        sa.Column("reconciled", sa.Boolean(), nullable=False),
        sa.Column("published_by", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("input_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_nav_publications_sha256_format")),
        sa.CheckConstraint(
            "nav = cash_value + positions_value - fees_value - taxes_value",
            name=op.f("ck_nav_publications_accounting_identity"),
        ),
        sa.CheckConstraint("revision > 0", name=op.f("ck_nav_publications_positive_revision")),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["model_portfolios.id"],
            name=op.f("fk_nav_publications_portfolio_id_model_portfolios"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_version_id"],
            ["institutional_portfolio_versions.id"],
            name=op.f("fk_nav_publications_portfolio_version_id_institutional_portfolio_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nav_publications")),
        sa.UniqueConstraint("portfolio_id", "as_of", "revision", name="uq_nav_publications_portfolio_asof_revision"),
    )
    op.create_index(op.f("ix_nav_publications_portfolio_id"), "nav_publications", ["portfolio_id"], unique=False)
    op.create_table(
        "portfolio_ledger_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("portfolio_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=True),
        sa.Column("entry_type", sa.String(length=30), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("amount", sa.Numeric(precision=28, scale=8), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_reference", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "entry_type IN ('cash', 'trade', 'dividend', 'jcp', 'fee', 'tax', 'fx')",
            name=op.f("ck_portfolio_ledger_entries_entry_type_values"),
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_portfolio_ledger_entries_instrument_id_instruments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["model_portfolios.id"],
            name=op.f("fk_portfolio_ledger_entries_portfolio_id_model_portfolios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_ledger_entries")),
        sa.UniqueConstraint("portfolio_id", "source_reference", name="uq_portfolio_ledger_entries_source"),
    )
    op.create_index(
        op.f("ix_portfolio_ledger_entries_occurred_at"), "portfolio_ledger_entries", ["occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_portfolio_ledger_entries_portfolio_id"), "portfolio_ledger_entries", ["portfolio_id"], unique=False
    )
    op.create_table(
        "position_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("portfolio_version_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("cost_basis", sa.Numeric(precision=28, scale=8), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("quantity >= 0 AND cost_basis >= 0", name=op.f("ck_position_snapshots_nonnegative_values")),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_position_snapshots_instrument_id_instruments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_version_id"],
            ["institutional_portfolio_versions.id"],
            name=op.f("fk_position_snapshots_portfolio_version_id_institutional_portfolio_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_position_snapshots")),
        sa.UniqueConstraint("portfolio_version_id", "instrument_id", name="uq_position_snapshots_version_instrument"),
    )
    op.create_index(
        op.f("ix_position_snapshots_portfolio_version_id"), "position_snapshots", ["portfolio_version_id"], unique=False
    )
    op.create_table(
        "risk_breaches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("risk_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("limit_name", sa.String(length=150), nullable=False),
        sa.Column("limit_type", sa.String(length=10), nullable=False),
        sa.Column("observed_value", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("limit_value", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("limit_type IN ('hard', 'soft')", name=op.f("ck_risk_breaches_limit_type_values")),
        sa.CheckConstraint("status IN ('open', 'waived', 'resolved')", name=op.f("ck_risk_breaches_status_values")),
        sa.ForeignKeyConstraint(
            ["risk_snapshot_id"],
            ["institutional_risk_snapshots.id"],
            name=op.f("fk_risk_breaches_risk_snapshot_id_institutional_risk_snapshots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_breaches")),
        sa.UniqueConstraint("risk_snapshot_id", "limit_name", name="uq_risk_breaches_snapshot_limit"),
    )
    op.create_index(op.f("ix_risk_breaches_risk_snapshot_id"), "risk_breaches", ["risk_snapshot_id"], unique=False)
    op.create_table(
        "stress_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("risk_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("scenario_id", sa.Uuid(), nullable=False),
        sa.Column("pnl_impact", sa.Numeric(precision=28, scale=8), nullable=False),
        sa.Column("nav_impact_ratio", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("result_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["risk_snapshot_id"],
            ["institutional_risk_snapshots.id"],
            name=op.f("fk_stress_results_risk_snapshot_id_institutional_risk_snapshots"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["stress_scenarios.id"],
            name=op.f("fk_stress_results_scenario_id_stress_scenarios"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stress_results")),
        sa.UniqueConstraint("risk_snapshot_id", "scenario_id", name="uq_stress_results_snapshot_scenario"),
    )
    op.create_index(op.f("ix_stress_results_risk_snapshot_id"), "stress_results", ["risk_snapshot_id"], unique=False)
    op.create_table(
        "risk_waivers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("breach_id", sa.Uuid(), nullable=False),
        sa.Column("granted_by", sa.String(length=255), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("expires_at > granted_at", name=op.f("ck_risk_waivers_valid_expiry")),
        sa.ForeignKeyConstraint(
            ["breach_id"],
            ["risk_breaches.id"],
            name=op.f("fk_risk_waivers_breach_id_risk_breaches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_waivers")),
    )
    op.create_index(op.f("ix_risk_waivers_breach_id"), "risk_waivers", ["breach_id"], unique=False)
    op.create_table(
        "portfolio_version_theses",
        sa.Column("portfolio_version_id", sa.Uuid(), nullable=False),
        sa.Column("thesis_version_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["portfolio_version_id"],
            ["institutional_portfolio_versions.id"],
            name=op.f("fk_portfolio_version_theses_portfolio_version_id_institutional_portfolio_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["thesis_version_id"],
            ["research_thesis_versions.id"],
            name=op.f("fk_portfolio_version_theses_thesis_version_id_research_thesis_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("portfolio_version_id", "thesis_version_id", name=op.f("pk_portfolio_version_theses")),
    )
    op.create_table(
        "portfolio_version_valuations",
        sa.Column("portfolio_version_id", sa.Uuid(), nullable=False),
        sa.Column("valuation_run_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["portfolio_version_id"],
            ["institutional_portfolio_versions.id"],
            name=op.f("fk_portfolio_version_valuations_portfolio_version_id_institutional_portfolio_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["valuation_run_id"],
            ["valuation_runs.id"],
            name=op.f("fk_portfolio_version_valuations_valuation_run_id_valuation_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "portfolio_version_id", "valuation_run_id", name=op.f("pk_portfolio_version_valuations")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("portfolio_version_valuations")
    op.drop_table("portfolio_version_theses")
    op.drop_index(op.f("ix_risk_waivers_breach_id"), table_name="risk_waivers")
    op.drop_table("risk_waivers")
    op.drop_index(op.f("ix_stress_results_risk_snapshot_id"), table_name="stress_results")
    op.drop_table("stress_results")
    op.drop_index(op.f("ix_risk_breaches_risk_snapshot_id"), table_name="risk_breaches")
    op.drop_table("risk_breaches")
    op.drop_index(op.f("ix_position_snapshots_portfolio_version_id"), table_name="position_snapshots")
    op.drop_table("position_snapshots")
    op.drop_index(op.f("ix_portfolio_ledger_entries_portfolio_id"), table_name="portfolio_ledger_entries")
    op.drop_index(op.f("ix_portfolio_ledger_entries_occurred_at"), table_name="portfolio_ledger_entries")
    op.drop_table("portfolio_ledger_entries")
    op.drop_index(op.f("ix_nav_publications_portfolio_id"), table_name="nav_publications")
    op.drop_table("nav_publications")
    op.drop_index(
        op.f("ix_institutional_risk_snapshots_portfolio_version_id"), table_name="institutional_risk_snapshots"
    )
    op.drop_table("institutional_risk_snapshots")
    op.drop_index(op.f("ix_cash_snapshots_portfolio_version_id"), table_name="cash_snapshots")
    op.drop_table("cash_snapshots")
    op.drop_index(op.f("ix_optimization_runs_portfolio_id"), table_name="optimization_runs")
    op.drop_table("optimization_runs")
    op.drop_index(
        op.f("ix_institutional_portfolio_versions_portfolio_id"), table_name="institutional_portfolio_versions"
    )
    op.drop_table("institutional_portfolio_versions")
    op.drop_table("team_memberships")
    op.drop_table("role_permissions")
    op.drop_index(op.f("ix_model_portfolios_organization_id"), table_name="model_portfolios")
    op.drop_table("model_portfolios")
    op.drop_table("membership_roles")
    op.drop_index(op.f("ix_institutional_risk_policies_mandate_id"), table_name="institutional_risk_policies")
    op.drop_table("institutional_risk_policies")
    op.drop_index(op.f("ix_institutional_backtest_runs_config_id"), table_name="institutional_backtest_runs")
    op.drop_table("institutional_backtest_runs")
    op.drop_index(op.f("ix_teams_organization_id"), table_name="teams")
    op.drop_table("teams")
    op.drop_index(op.f("ix_strategy_mandates_organization_id"), table_name="strategy_mandates")
    op.drop_table("strategy_mandates")
    op.drop_index(op.f("ix_service_identities_organization_id"), table_name="service_identities")
    op.drop_table("service_identities")
    op.drop_table("roles")
    op.drop_index(op.f("ix_organization_memberships_user_id"), table_name="organization_memberships")
    op.drop_index(op.f("ix_organization_memberships_organization_id"), table_name="organization_memberships")
    op.drop_table("organization_memberships")
    op.drop_index(op.f("ix_backtest_configs_organization_id"), table_name="backtest_configs")
    op.drop_table("backtest_configs")
    op.drop_table("user_identities")
    op.drop_table("stress_scenarios")
    op.drop_table("permissions")
    op.drop_table("organizations")
    # ### end Alembic commands ###
