"""controlled production readiness gate

Revision ID: 6904a13eb7a7
Revises: 9ba08391c38d
Create Date: 2026-07-19 05:09:54.256994
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "6904a13eb7a7"
down_revision: str | Sequence[str] | None = "9ba08391c38d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "readiness_controls",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("control_key", sa.String(length=100), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("domain", sa.String(length=30), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("control_type", sa.String(length=20), nullable=False),
        sa.Column("owner_role", sa.String(length=100), nullable=False),
        sa.Column("frequency", sa.String(length=50), nullable=False),
        sa.Column("test_procedure", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "control_type IN ('preventive', 'detective', 'corrective')",
            name=op.f("ck_readiness_controls_control_type_values"),
        ),
        sa.CheckConstraint(
            "domain IN ('legal', 'data', 'security', 'operations', 'model_risk', 'investments', 'compliance')",
            name=op.f("ck_readiness_controls_domain_values"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'effective', 'ineffective', 'retired')",
            name=op.f("ck_readiness_controls_status_values"),
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from", name=op.f("ck_readiness_controls_valid_window")
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_readiness_controls_positive_version")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_readiness_controls_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_readiness_controls")),
        sa.UniqueConstraint("organization_id", "control_key", "version", name="uq_readiness_controls_org_key_version"),
    )
    op.create_index(
        op.f("ix_readiness_controls_organization_id"), "readiness_controls", ["organization_id"], unique=False
    )
    op.create_table(
        "readiness_decision_packs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("frozen_by", sa.String(length=200), nullable=False),
        sa.Column("frozen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("content_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_readiness_decision_packs_sha256_format")),
        sa.CheckConstraint("expires_at > frozen_at", name=op.f("ck_readiness_decision_packs_valid_window")),
        sa.CheckConstraint("version > 0", name=op.f("ck_readiness_decision_packs_positive_version")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_readiness_decision_packs_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_readiness_decision_packs")),
        sa.UniqueConstraint("organization_id", "content_sha256", name="uq_readiness_packs_org_hash"),
        sa.UniqueConstraint("organization_id", "version", name="uq_readiness_packs_org_version"),
    )
    op.create_index(
        op.f("ix_readiness_decision_packs_organization_id"),
        "readiness_decision_packs",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "readiness_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_type", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("artifact_uri", sa.Text(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("issued_by", sa.String(length=250), nullable=False),
        sa.Column("independent", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_by", sa.String(length=200), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint("content_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_readiness_evidence_sha256_format")),
        sa.CheckConstraint(
            "status <> 'verified' OR (verified_by IS NOT NULL AND verified_at IS NOT NULL)",
            name=op.f("ck_readiness_evidence_verification_is_attributed"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'verified', 'rejected', 'expired')", name=op.f("ck_readiness_evidence_status_values")
        ),
        sa.CheckConstraint(
            "expires_at IS NULL OR expires_at > issued_at", name=op.f("ck_readiness_evidence_valid_window")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_readiness_evidence_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_readiness_evidence")),
        sa.UniqueConstraint("organization_id", "content_sha256", name="uq_readiness_evidence_org_hash"),
    )
    op.create_index(
        op.f("ix_readiness_evidence_organization_id"), "readiness_evidence", ["organization_id"], unique=False
    )
    op.create_table(
        "readiness_control_evidence",
        sa.Column("control_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("linked_by", sa.String(length=200), nullable=False),
        sa.Column("linked_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["control_id"],
            ["readiness_controls.id"],
            name=op.f("fk_readiness_control_evidence_control_id_readiness_controls"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["readiness_evidence.id"],
            name=op.f("fk_readiness_control_evidence_evidence_id_readiness_evidence"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("control_id", "evidence_id", name=op.f("pk_readiness_control_evidence")),
    )
    op.create_table(
        "readiness_decisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("decision_pack_id", sa.Uuid(), nullable=False),
        sa.Column("result", sa.String(length=30), nullable=False),
        sa.Column("authorized_scope", sa.String(length=50), nullable=False),
        sa.Column("blockers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dissent", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("decided_by", sa.String(length=200), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(result = 'go' AND authorized_scope = 'future_live_planning') OR "
            "(result = 'conditional_go' AND authorized_scope = 'remediation_only') OR "
            "(result = 'no_go' AND authorized_scope = 'none')",
            name=op.f("ck_readiness_decisions_result_scope_consistency"),
        ),
        sa.CheckConstraint(
            "authorized_scope IN ('none', 'remediation_only', 'future_live_planning')",
            name=op.f("ck_readiness_decisions_authorized_scope_values"),
        ),
        sa.CheckConstraint(
            "result IN ('go', 'conditional_go', 'no_go')", name=op.f("ck_readiness_decisions_result_values")
        ),
        sa.CheckConstraint("expires_at > decided_at", name=op.f("ck_readiness_decisions_valid_window")),
        sa.ForeignKeyConstraint(
            ["decision_pack_id"],
            ["readiness_decision_packs.id"],
            name=op.f("fk_readiness_decisions_decision_pack_id_readiness_decision_packs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_readiness_decisions")),
        sa.UniqueConstraint("decision_pack_id", name=op.f("uq_readiness_decisions_decision_pack_id")),
    )
    op.create_table(
        "readiness_findings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("domain", sa.String(length=30), nullable=False),
        sa.Column("finding_key", sa.String(length=120), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("owner_role", sa.String(length=100), nullable=False),
        sa.Column("remediation", sa.Text(), nullable=True),
        sa.Column("exception_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retest_evidence_id", sa.Uuid(), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "severity IN ('low', 'medium', 'high', 'critical')", name=op.f("ck_readiness_findings_severity_values")
        ),
        sa.CheckConstraint(
            "status <> 'closed' OR (closed_at IS NOT NULL AND retest_evidence_id IS NOT NULL)",
            name=op.f("ck_readiness_findings_closure_requires_retest"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'remediating', 'closed', 'risk_accepted')",
            name=op.f("ck_readiness_findings_status_values"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_readiness_findings_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["retest_evidence_id"],
            ["readiness_evidence.id"],
            name=op.f("fk_readiness_findings_retest_evidence_id_readiness_evidence"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_readiness_findings")),
        sa.UniqueConstraint("organization_id", "finding_key", name="uq_readiness_findings_org_key"),
    )
    op.create_index(
        op.f("ix_readiness_findings_organization_id"), "readiness_findings", ["organization_id"], unique=False
    )
    op.create_table(
        "readiness_votes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("decision_pack_id", sa.Uuid(), nullable=False),
        sa.Column("voter_subject", sa.String(length=200), nullable=False),
        sa.Column("voter_role", sa.String(length=50), nullable=False),
        sa.Column("vote", sa.String(length=30), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("conflicts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("signed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("vote IN ('go', 'conditional_go', 'no_go')", name=op.f("ck_readiness_votes_vote_values")),
        sa.CheckConstraint(
            "voter_role IN ('legal', 'security', 'risk', 'compliance', 'operations', 'data', 'investments')",
            name=op.f("ck_readiness_votes_voter_role_values"),
        ),
        sa.ForeignKeyConstraint(
            ["decision_pack_id"],
            ["readiness_decision_packs.id"],
            name=op.f("fk_readiness_votes_decision_pack_id_readiness_decision_packs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_readiness_votes")),
        sa.UniqueConstraint("decision_pack_id", "voter_role", name="uq_readiness_votes_pack_role"),
    )
    op.create_index(op.f("ix_readiness_votes_decision_pack_id"), "readiness_votes", ["decision_pack_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_readiness_votes_decision_pack_id"), table_name="readiness_votes")
    op.drop_table("readiness_votes")
    op.drop_index(op.f("ix_readiness_findings_organization_id"), table_name="readiness_findings")
    op.drop_table("readiness_findings")
    op.drop_table("readiness_decisions")
    op.drop_table("readiness_control_evidence")
    op.drop_index(op.f("ix_readiness_evidence_organization_id"), table_name="readiness_evidence")
    op.drop_table("readiness_evidence")
    op.drop_index(op.f("ix_readiness_decision_packs_organization_id"), table_name="readiness_decision_packs")
    op.drop_table("readiness_decision_packs")
    op.drop_index(op.f("ix_readiness_controls_organization_id"), table_name="readiness_controls")
    op.drop_table("readiness_controls")
    # ### end Alembic commands ###
