"""agent runtime idempotency

Revision ID: 6a3f5c22421b
Revises: 2a3d784c8e65
Create Date: 2026-07-19 04:38:44.419935
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6a3f5c22421b"
down_revision: str | Sequence[str] | None = "2a3d784c8e65"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent_runtime_runs", sa.Column("idempotency_key", sa.String(length=255), nullable=True))
    op.create_unique_constraint(
        "uq_agent_runtime_runs_capability_idempotency", "agent_runtime_runs", ["capability_id", "idempotency_key"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_agent_runtime_runs_capability_idempotency", "agent_runtime_runs", type_="unique")
    op.drop_column("agent_runtime_runs", "idempotency_key")
    # ### end Alembic commands ###
