"""paper execution operations

Revision ID: 9ba08391c38d
Revises: d648bc5143e1
Create Date: 2026-07-19 05:03:35.360401
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "9ba08391c38d"
down_revision: str | Sequence[str] | None = "d648bc5143e1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "execution_model_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("logical_id", sa.String(length=100), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("content_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_execution_model_versions_sha256_format")),
        sa.CheckConstraint(
            "status IN ('draft', 'approved', 'retired')", name=op.f("ck_execution_model_versions_status_values")
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_execution_model_versions_positive_version")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_execution_model_versions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_execution_model_versions")),
        sa.UniqueConstraint("organization_id", "logical_id", "version", name="uq_execution_models_org_logical_version"),
    )
    op.create_index(
        op.f("ix_execution_model_versions_organization_id"),
        "execution_model_versions",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "challenger_evaluations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("mandate_id", sa.Uuid(), nullable=False),
        sa.Column("champion_portfolio_id", sa.Uuid(), nullable=False),
        sa.Column("challenger_portfolio_id", sa.Uuid(), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("methodology_version", sa.String(length=100), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("decision", sa.String(length=30), nullable=False),
        sa.Column("decided_by", sa.String(length=200), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "decision = 'pending_committee' OR decided_by IS NOT NULL",
            name=op.f("ck_challenger_evaluations_decision_requires_human"),
        ),
        sa.CheckConstraint(
            "decision IN ('pending_committee', 'retained', 'promoted', 'rejected')",
            name=op.f("ck_challenger_evaluations_decision_values"),
        ),
        sa.CheckConstraint(
            "champion_portfolio_id <> challenger_portfolio_id",
            name=op.f("ck_challenger_evaluations_different_portfolios"),
        ),
        sa.CheckConstraint("window_end > window_start", name=op.f("ck_challenger_evaluations_valid_window")),
        sa.ForeignKeyConstraint(
            ["challenger_portfolio_id"],
            ["model_portfolios.id"],
            name=op.f("fk_challenger_evaluations_challenger_portfolio_id_model_portfolios"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["champion_portfolio_id"],
            ["model_portfolios.id"],
            name=op.f("fk_challenger_evaluations_champion_portfolio_id_model_portfolios"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["mandate_id"],
            ["strategy_mandates.id"],
            name=op.f("fk_challenger_evaluations_mandate_id_strategy_mandates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_challenger_evaluations")),
        sa.UniqueConstraint(
            "mandate_id",
            "challenger_portfolio_id",
            "window_start",
            "window_end",
            name="uq_challenger_evaluation_window",
        ),
    )
    op.create_index(
        op.f("ix_challenger_evaluations_mandate_id"), "challenger_evaluations", ["mandate_id"], unique=False
    )
    op.create_table(
        "operational_alerts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("portfolio_id", sa.Uuid(), nullable=True),
        sa.Column("deduplication_key", sa.String(length=250), nullable=False),
        sa.Column("alert_type", sa.String(length=80), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("acknowledged_by", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "severity IN ('info', 'warning', 'critical')", name=op.f("ck_operational_alerts_severity_values")
        ),
        sa.CheckConstraint(
            "status IN ('open', 'acknowledged', 'resolved')", name=op.f("ck_operational_alerts_status_values")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_operational_alerts_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["model_portfolios.id"],
            name=op.f("fk_operational_alerts_portfolio_id_model_portfolios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operational_alerts")),
        sa.UniqueConstraint("organization_id", "deduplication_key", name="uq_operational_alerts_org_dedup"),
    )
    op.create_index(
        op.f("ix_operational_alerts_organization_id"), "operational_alerts", ["organization_id"], unique=False
    )
    op.create_table(
        "paper_kill_switches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("portfolio_id", sa.Uuid(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("activated_by", sa.String(length=200), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("released_by", sa.String(length=200), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "active OR (released_by IS NOT NULL AND released_at IS NOT NULL)",
            name=op.f("ck_paper_kill_switches_release_is_attributed"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_paper_kill_switches_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["model_portfolios.id"],
            name=op.f("fk_paper_kill_switches_portfolio_id_model_portfolios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paper_kill_switches")),
    )
    op.create_index(
        op.f("ix_paper_kill_switches_organization_id"), "paper_kill_switches", ["organization_id"], unique=False
    )
    op.create_table(
        "paper_post_mortems",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("portfolio_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expected", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("realized", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attribution", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("findings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dissent", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("content_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_paper_post_mortems_sha256_format")),
        sa.CheckConstraint("period_end > period_start", name=op.f("ck_paper_post_mortems_valid_period")),
        sa.CheckConstraint("version > 0", name=op.f("ck_paper_post_mortems_positive_version")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_paper_post_mortems_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["model_portfolios.id"],
            name=op.f("fk_paper_post_mortems_portfolio_id_model_portfolios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paper_post_mortems")),
        sa.UniqueConstraint("portfolio_id", "version", name="uq_paper_post_mortems_portfolio_version"),
    )
    op.create_index(
        op.f("ix_paper_post_mortems_organization_id"), "paper_post_mortems", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_paper_post_mortems_portfolio_id"), "paper_post_mortems", ["portfolio_id"], unique=False)
    op.create_table(
        "paper_reconciliation_breaks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("portfolio_id", sa.Uuid(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rule", sa.String(length=100), nullable=False),
        sa.Column("resource_key", sa.String(length=200), nullable=False),
        sa.Column("expected", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("actual", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("blocking", sa.Boolean(), nullable=False),
        sa.Column("resolution", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "NOT blocking OR severity = 'critical'", name=op.f("ck_paper_reconciliation_breaks_only_critical_blocks")
        ),
        sa.CheckConstraint(
            "severity IN ('info', 'warning', 'critical')", name=op.f("ck_paper_reconciliation_breaks_severity_values")
        ),
        sa.CheckConstraint(
            "status IN ('open', 'acknowledged', 'resolved', 'waived')",
            name=op.f("ck_paper_reconciliation_breaks_status_values"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_paper_reconciliation_breaks_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["model_portfolios.id"],
            name=op.f("fk_paper_reconciliation_breaks_portfolio_id_model_portfolios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paper_reconciliation_breaks")),
        sa.UniqueConstraint("portfolio_id", "as_of", "rule", "resource_key", name="uq_reconciliation_break_identity"),
    )
    op.create_index(
        op.f("ix_paper_reconciliation_breaks_organization_id"),
        "paper_reconciliation_breaks",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paper_reconciliation_breaks_portfolio_id"),
        "paper_reconciliation_breaks",
        ["portfolio_id"],
        unique=False,
    )
    op.create_table(
        "paper_trade_intents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("portfolio_id", sa.Uuid(), nullable=False),
        sa.Column("portfolio_version_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("order_type", sa.String(length=20), nullable=False),
        sa.Column("limit_price", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("earliest_execution_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("approval_decision", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("environment", sa.String(length=10), nullable=False),
        sa.Column("created_by", sa.String(length=200), nullable=False),
        sa.Column("approved_by", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(order_type = 'limit') = (limit_price IS NOT NULL)",
            name=op.f("ck_paper_trade_intents_limit_price_required"),
        ),
        sa.CheckConstraint("environment = 'paper'", name=op.f("ck_paper_trade_intents_paper_only")),
        sa.CheckConstraint("order_type IN ('market', 'limit')", name=op.f("ck_paper_trade_intents_order_type_values")),
        sa.CheckConstraint("side IN ('buy', 'sell')", name=op.f("ck_paper_trade_intents_side_values")),
        sa.CheckConstraint(
            "status IN ('draft', 'pending_approval', 'approved', 'submitted', "
            "'completed', 'cancelled', 'expired', 'failed')",
            name=op.f("ck_paper_trade_intents_status_values"),
        ),
        sa.CheckConstraint(
            "expires_at > earliest_execution_at", name=op.f("ck_paper_trade_intents_valid_execution_window")
        ),
        sa.CheckConstraint(
            "limit_price IS NULL OR limit_price > 0", name=op.f("ck_paper_trade_intents_positive_limit_price")
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_paper_trade_intents_positive_quantity")),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_paper_trade_intents_instrument_id_instruments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_paper_trade_intents_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["model_portfolios.id"],
            name=op.f("fk_paper_trade_intents_portfolio_id_model_portfolios"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_version_id"],
            ["institutional_portfolio_versions.id"],
            name=op.f("fk_paper_trade_intents_portfolio_version_id_institutional_portfolio_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paper_trade_intents")),
        sa.UniqueConstraint("organization_id", "idempotency_key", name="uq_trade_intents_org_idempotency"),
    )
    op.create_index(
        op.f("ix_paper_trade_intents_organization_id"), "paper_trade_intents", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_paper_trade_intents_portfolio_id"), "paper_trade_intents", ["portfolio_id"], unique=False)
    op.create_index(
        op.f("ix_paper_trade_intents_portfolio_version_id"),
        "paper_trade_intents",
        ["portfolio_version_id"],
        unique=False,
    )
    op.create_table(
        "paper_orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("trade_intent_id", sa.Uuid(), nullable=False),
        sa.Column("execution_model_version_id", sa.Uuid(), nullable=False),
        sa.Column("submit_key", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("requested_quantity", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("filled_quantity", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("input_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("input_sha256", sa.String(length=64), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("environment", sa.String(length=10), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("environment = 'paper'", name=op.f("ck_paper_orders_paper_only")),
        sa.CheckConstraint("input_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_paper_orders_sha256_format")),
        sa.CheckConstraint(
            "status IN ('created', 'accepted', 'partially_filled', 'filled', 'cancelled', 'rejected', 'expired')",
            name=op.f("ck_paper_orders_status_values"),
        ),
        sa.CheckConstraint(
            "filled_quantity >= 0 AND filled_quantity <= requested_quantity",
            name=op.f("ck_paper_orders_valid_filled_quantity"),
        ),
        sa.CheckConstraint("requested_quantity > 0", name=op.f("ck_paper_orders_positive_requested_quantity")),
        sa.ForeignKeyConstraint(
            ["execution_model_version_id"],
            ["execution_model_versions.id"],
            name=op.f("fk_paper_orders_execution_model_version_id_execution_model_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["trade_intent_id"],
            ["paper_trade_intents.id"],
            name=op.f("fk_paper_orders_trade_intent_id_paper_trade_intents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paper_orders")),
        sa.UniqueConstraint("submit_key", name=op.f("uq_paper_orders_submit_key")),
    )
    op.create_index(op.f("ix_paper_orders_trade_intent_id"), "paper_orders", ["trade_intent_id"], unique=False)
    op.create_table(
        "paper_fills",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("event_key", sa.String(length=200), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("price", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("gross_value", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("fee_value", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("tax_value", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("slippage_bps", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("market_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("filled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("environment", sa.String(length=10), nullable=False),
        sa.CheckConstraint("environment = 'paper'", name=op.f("ck_paper_fills_paper_only")),
        sa.CheckConstraint("fee_value >= 0 AND tax_value >= 0", name=op.f("ck_paper_fills_nonnegative_costs")),
        sa.CheckConstraint("gross_value = quantity * price", name=op.f("ck_paper_fills_gross_value_identity")),
        sa.CheckConstraint("quantity > 0 AND price > 0", name=op.f("ck_paper_fills_positive_fill")),
        sa.CheckConstraint("sequence > 0", name=op.f("ck_paper_fills_positive_sequence")),
        sa.ForeignKeyConstraint(
            ["order_id"], ["paper_orders.id"], name=op.f("fk_paper_fills_order_id_paper_orders"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paper_fills")),
        sa.UniqueConstraint("event_key", name=op.f("uq_paper_fills_event_key")),
        sa.UniqueConstraint("order_id", "sequence", name="uq_paper_fills_order_sequence"),
    )
    op.create_index(op.f("ix_paper_fills_order_id"), "paper_fills", ["order_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_paper_fills_order_id"), table_name="paper_fills")
    op.drop_table("paper_fills")
    op.drop_index(op.f("ix_paper_orders_trade_intent_id"), table_name="paper_orders")
    op.drop_table("paper_orders")
    op.drop_index(op.f("ix_paper_trade_intents_portfolio_version_id"), table_name="paper_trade_intents")
    op.drop_index(op.f("ix_paper_trade_intents_portfolio_id"), table_name="paper_trade_intents")
    op.drop_index(op.f("ix_paper_trade_intents_organization_id"), table_name="paper_trade_intents")
    op.drop_table("paper_trade_intents")
    op.drop_index(op.f("ix_paper_reconciliation_breaks_portfolio_id"), table_name="paper_reconciliation_breaks")
    op.drop_index(op.f("ix_paper_reconciliation_breaks_organization_id"), table_name="paper_reconciliation_breaks")
    op.drop_table("paper_reconciliation_breaks")
    op.drop_index(op.f("ix_paper_post_mortems_portfolio_id"), table_name="paper_post_mortems")
    op.drop_index(op.f("ix_paper_post_mortems_organization_id"), table_name="paper_post_mortems")
    op.drop_table("paper_post_mortems")
    op.drop_index(op.f("ix_paper_kill_switches_organization_id"), table_name="paper_kill_switches")
    op.drop_table("paper_kill_switches")
    op.drop_index(op.f("ix_operational_alerts_organization_id"), table_name="operational_alerts")
    op.drop_table("operational_alerts")
    op.drop_index(op.f("ix_challenger_evaluations_mandate_id"), table_name="challenger_evaluations")
    op.drop_table("challenger_evaluations")
    op.drop_index(op.f("ix_execution_model_versions_organization_id"), table_name="execution_model_versions")
    op.drop_table("execution_model_versions")
    # ### end Alembic commands ###
