"""champion challenger comparison governance

Revision ID: d17057502a53
Revises: f89dcda6c0a2
Create Date: 2026-07-19 05:26:27.492323
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "d17057502a53"
down_revision: str | Sequence[str] | None = "f89dcda6c0a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("challenger_evaluations", sa.Column("comparison_sha256", sa.String(length=64), nullable=False))
    op.add_column(
        "challenger_evaluations",
        sa.Column("comparison_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    op.add_column("challenger_evaluations", sa.Column("created_by", sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("challenger_evaluations", "created_by")
    op.drop_column("challenger_evaluations", "comparison_config")
    op.drop_column("challenger_evaluations", "comparison_sha256")
    # ### end Alembic commands ###
