"""policy intelligence graph and macro revisions

Revision ID: d648bc5143e1
Revises: 6a3f5c22421b
Create Date: 2026-07-19 04:54:39.592685
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "d648bc5143e1"
down_revision: str | Sequence[str] | None = "6a3f5c22421b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "policy_actors",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("authority", sa.String(length=100), nullable=False),
        sa.Column("external_id", sa.String(length=150), nullable=False),
        sa.Column("display_name", sa.String(length=250), nullable=False),
        sa.Column("actor_type", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_actors")),
        sa.UniqueConstraint("authority", "external_id", name="uq_policy_actors_authority_external"),
    )
    op.create_table(
        "policy_objects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("jurisdiction", sa.String(length=20), nullable=False),
        sa.Column("authority", sa.String(length=100), nullable=False),
        sa.Column("object_type", sa.String(length=50), nullable=False),
        sa.Column("external_id", sa.String(length=150), nullable=False),
        sa.Column("canonical_key", sa.String(length=300), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_objects")),
        sa.UniqueConstraint("canonical_key", name=op.f("uq_policy_objects_canonical_key")),
    )
    op.create_table(
        "policy_graph_nodes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("node_type", sa.String(length=30), nullable=False),
        sa.Column("reference_id", sa.Uuid(), nullable=True),
        sa.Column("logical_key", sa.String(length=250), nullable=False),
        sa.Column("label", sa.String(length=250), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_policy_graph_nodes_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_graph_nodes")),
        sa.UniqueConstraint("organization_id", "node_type", "logical_key", name="uq_policy_graph_nodes_scope_type_key"),
    )
    op.create_index(
        op.f("ix_policy_graph_nodes_organization_id"), "policy_graph_nodes", ["organization_id"], unique=False
    )
    op.create_table(
        "policy_probability_forecasts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("policy_object_id", sa.Uuid(), nullable=False),
        sa.Column("target_outcome", sa.String(length=100), nullable=False),
        sa.Column("methodology_version", sa.String(length=100), nullable=False),
        sa.Column("features_sha256", sa.String(length=64), nullable=False),
        sa.Column("probability", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("interval_low", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("interval_high", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("assumptions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("factors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("predicted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("knowledge_cutoff", sa.DateTime(timezone=True), nullable=False),
        sa.Column("outcome", sa.Boolean(), nullable=True),
        sa.Column("outcome_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "features_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_policy_probability_forecasts_sha256_format")
        ),
        sa.CheckConstraint(
            "0 <= interval_low AND interval_low <= probability AND probability <= interval_high AND interval_high <= 1",
            name=op.f("ck_policy_probability_forecasts_valid_interval"),
        ),
        sa.CheckConstraint(
            "outcome_at IS NULL OR outcome IS NOT NULL",
            name=op.f("ck_policy_probability_forecasts_outcome_consistency"),
        ),
        sa.ForeignKeyConstraint(
            ["policy_object_id"],
            ["policy_objects.id"],
            name=op.f("fk_policy_probability_forecasts_policy_object_id_policy_objects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_probability_forecasts")),
        sa.UniqueConstraint(
            "policy_object_id",
            "target_outcome",
            "methodology_version",
            "predicted_at",
            name="uq_policy_forecasts_target_time",
        ),
    )
    op.create_index(
        op.f("ix_policy_probability_forecasts_policy_object_id"),
        "policy_probability_forecasts",
        ["policy_object_id"],
        unique=False,
    )
    op.create_table(
        "macro_series_definitions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("series_code", sa.String(length=100), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("unit", sa.String(length=50), nullable=False),
        sa.Column("frequency", sa.String(length=30), nullable=False),
        sa.Column("revision_policy", sa.String(length=100), nullable=False),
        sa.Column("transformation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("content_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_macro_series_definitions_sha256_format")),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from", name=op.f("ck_macro_series_definitions_valid_window")
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_macro_series_definitions_positive_version")),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
            name=op.f("fk_macro_series_definitions_source_id_data_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_macro_series_definitions")),
        sa.UniqueConstraint(
            "source_id", "series_code", "version", name="uq_macro_series_definitions_source_code_version"
        ),
    )
    op.create_table(
        "macro_observation_revisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("series_definition_id", sa.Uuid(), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("value", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("value_status", sa.String(length=30), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("knowledge_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_object_version_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "(value_status = 'reported') = (value IS NOT NULL)",
            name=op.f("ck_macro_observation_revisions_value_matches_status"),
        ),
        sa.CheckConstraint(
            "value_status IN ('reported', 'missing', 'suppressed', 'parse_error')",
            name=op.f("ck_macro_observation_revisions_value_status_values"),
        ),
        sa.CheckConstraint("revision > 0", name=op.f("ck_macro_observation_revisions_positive_revision")),
        sa.ForeignKeyConstraint(
            ["series_definition_id"],
            ["macro_series_definitions.id"],
            name=op.f("fk_macro_observation_revisions_series_definition_id_macro_series_definitions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_object_version_id"],
            ["source_object_versions.id"],
            name=op.f("fk_macro_observation_revisions_source_object_version_id_source_object_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_macro_observation_revisions")),
        sa.UniqueConstraint(
            "series_definition_id", "effective_date", "revision", name="uq_macro_observations_series_date_revision"
        ),
    )
    op.create_index(
        op.f("ix_macro_observation_revisions_knowledge_at"),
        "macro_observation_revisions",
        ["knowledge_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_macro_observation_revisions_series_definition_id"),
        "macro_observation_revisions",
        ["series_definition_id"],
        unique=False,
    )
    op.create_table(
        "policy_object_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("policy_object_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("text_sha256", sa.String(length=64), nullable=False),
        sa.Column("metadata_sha256", sa.String(length=64), nullable=False),
        sa.Column("text_content", sa.Text(), nullable=False),
        sa.Column("metadata_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("diff_from_previous", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("knowledge_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_object_version_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "text_sha256 ~ '^[0-9a-f]{64}$' AND metadata_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_policy_object_versions_hash_format"),
        ),
        sa.ForeignKeyConstraint(
            ["policy_object_id"],
            ["policy_objects.id"],
            name=op.f("fk_policy_object_versions_policy_object_id_policy_objects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_object_version_id"],
            ["source_object_versions.id"],
            name=op.f("fk_policy_object_versions_source_object_version_id_source_object_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_object_versions")),
        sa.UniqueConstraint(
            "policy_object_id", "text_sha256", "metadata_sha256", name="uq_policy_object_versions_content"
        ),
        sa.UniqueConstraint("policy_object_id", "version", name="uq_policy_object_versions_object_version"),
    )
    op.create_index(
        op.f("ix_policy_object_versions_knowledge_at"), "policy_object_versions", ["knowledge_at"], unique=False
    )
    op.create_index(
        op.f("ix_policy_object_versions_policy_object_id"), "policy_object_versions", ["policy_object_id"], unique=False
    )
    op.create_table(
        "policy_corroborations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("policy_object_id", sa.Uuid(), nullable=False),
        sa.Column("assertion_sha256", sa.String(length=64), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("stance", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("knowledge_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("assertion_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_policy_corroborations_sha256_format")),
        sa.CheckConstraint(
            "stance IN ('supports', 'contradicts', 'neutral')", name=op.f("ck_policy_corroborations_stance_values")
        ),
        sa.CheckConstraint("confidence BETWEEN 0 AND 1", name=op.f("ck_policy_corroborations_confidence_range")),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["research_evidence.id"],
            name=op.f("fk_policy_corroborations_evidence_id_research_evidence"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["policy_object_id"],
            ["policy_objects.id"],
            name=op.f("fk_policy_corroborations_policy_object_id_policy_objects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_corroborations")),
        sa.UniqueConstraint(
            "policy_object_id", "assertion_sha256", "evidence_id", name="uq_policy_corroborations_assertion_evidence"
        ),
    )
    op.create_index(
        op.f("ix_policy_corroborations_policy_object_id"), "policy_corroborations", ["policy_object_id"], unique=False
    )
    op.create_table(
        "policy_graph_edges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("from_node_id", sa.Uuid(), nullable=False),
        sa.Column("to_node_id", sa.Uuid(), nullable=False),
        sa.Column("relationship", sa.String(length=50), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("method", sa.String(length=100), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("weight", sa.Numeric(precision=12, scale=8), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('draft', 'approved', 'retired')", name=op.f("ck_policy_graph_edges_status_values")
        ),
        sa.CheckConstraint("confidence BETWEEN 0 AND 1", name=op.f("ck_policy_graph_edges_confidence_range")),
        sa.CheckConstraint("from_node_id <> to_node_id", name=op.f("ck_policy_graph_edges_no_self_loop")),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from", name=op.f("ck_policy_graph_edges_valid_window")
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_policy_graph_edges_positive_version")),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["research_evidence.id"],
            name=op.f("fk_policy_graph_edges_evidence_id_research_evidence"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["from_node_id"],
            ["policy_graph_nodes.id"],
            name=op.f("fk_policy_graph_edges_from_node_id_policy_graph_nodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_node_id"],
            ["policy_graph_nodes.id"],
            name=op.f("fk_policy_graph_edges_to_node_id_policy_graph_nodes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_graph_edges")),
        sa.UniqueConstraint(
            "from_node_id", "to_node_id", "relationship", "version", name="uq_policy_graph_edges_version"
        ),
    )
    op.create_index(op.f("ix_policy_graph_edges_from_node_id"), "policy_graph_edges", ["from_node_id"], unique=False)
    op.create_index(op.f("ix_policy_graph_edges_to_node_id"), "policy_graph_edges", ["to_node_id"], unique=False)
    op.create_table(
        "policy_stage_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("policy_object_id", sa.Uuid(), nullable=False),
        sa.Column("stage", sa.String(length=80), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("knowledge_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("metadata_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["research_evidence.id"],
            name=op.f("fk_policy_stage_events_evidence_id_research_evidence"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["policy_object_id"],
            ["policy_objects.id"],
            name=op.f("fk_policy_stage_events_policy_object_id_policy_objects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_stage_events")),
        sa.UniqueConstraint(
            "policy_object_id", "stage", "occurred_at", "knowledge_at", name="uq_policy_stage_events_pit"
        ),
    )
    op.create_index(op.f("ix_policy_stage_events_knowledge_at"), "policy_stage_events", ["knowledge_at"], unique=False)
    op.create_index(
        op.f("ix_policy_stage_events_policy_object_id"), "policy_stage_events", ["policy_object_id"], unique=False
    )
    op.create_table(
        "policy_votes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("policy_object_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("vote_session_key", sa.String(length=150), nullable=False),
        sa.Column("position", sa.String(length=30), nullable=False),
        sa.Column("voted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("knowledge_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["policy_actors.id"], name=op.f("fk_policy_votes_actor_id_policy_actors"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["research_evidence.id"],
            name=op.f("fk_policy_votes_evidence_id_research_evidence"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["policy_object_id"],
            ["policy_objects.id"],
            name=op.f("fk_policy_votes_policy_object_id_policy_objects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_votes")),
        sa.UniqueConstraint("vote_session_key", "actor_id", name="uq_policy_votes_session_actor"),
    )
    op.create_index(op.f("ix_policy_votes_policy_object_id"), "policy_votes", ["policy_object_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_policy_votes_policy_object_id"), table_name="policy_votes")
    op.drop_table("policy_votes")
    op.drop_index(op.f("ix_policy_stage_events_policy_object_id"), table_name="policy_stage_events")
    op.drop_index(op.f("ix_policy_stage_events_knowledge_at"), table_name="policy_stage_events")
    op.drop_table("policy_stage_events")
    op.drop_index(op.f("ix_policy_graph_edges_to_node_id"), table_name="policy_graph_edges")
    op.drop_index(op.f("ix_policy_graph_edges_from_node_id"), table_name="policy_graph_edges")
    op.drop_table("policy_graph_edges")
    op.drop_index(op.f("ix_policy_corroborations_policy_object_id"), table_name="policy_corroborations")
    op.drop_table("policy_corroborations")
    op.drop_index(op.f("ix_policy_object_versions_policy_object_id"), table_name="policy_object_versions")
    op.drop_index(op.f("ix_policy_object_versions_knowledge_at"), table_name="policy_object_versions")
    op.drop_table("policy_object_versions")
    op.drop_index(op.f("ix_macro_observation_revisions_series_definition_id"), table_name="macro_observation_revisions")
    op.drop_index(op.f("ix_macro_observation_revisions_knowledge_at"), table_name="macro_observation_revisions")
    op.drop_table("macro_observation_revisions")
    op.drop_table("macro_series_definitions")
    op.drop_index(op.f("ix_policy_probability_forecasts_policy_object_id"), table_name="policy_probability_forecasts")
    op.drop_table("policy_probability_forecasts")
    op.drop_index(op.f("ix_policy_graph_nodes_organization_id"), table_name="policy_graph_nodes")
    op.drop_table("policy_graph_nodes")
    op.drop_table("policy_objects")
    op.drop_table("policy_actors")
    # ### end Alembic commands ###
