"""paper operations alert ownership

Revision ID: f89dcda6c0a2
Revises: 6904a13eb7a7
Create Date: 2026-07-19 05:23:50.467376
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f89dcda6c0a2"
down_revision: str | Sequence[str] | None = "6904a13eb7a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("operational_alerts", sa.Column("rule_version", sa.String(length=50), nullable=False))
    op.add_column("operational_alerts", sa.Column("route", sa.String(length=100), nullable=False))
    op.add_column("paper_reconciliation_breaks", sa.Column("owner_role", sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("paper_reconciliation_breaks", "owner_role")
    op.drop_column("operational_alerts", "route")
    op.drop_column("operational_alerts", "rule_version")
    # ### end Alembic commands ###
