"""initial schema

Revision ID: fd3d46f598f2
Revises:
Create Date: 2026-07-18 23:39:35.690744

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fd3d46f598f2"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("operation_type", sa.String(length=100), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("request_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("result_url", sa.Text(), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "state IN ('pending', 'running', 'succeeded', 'failed', 'cancelled')",
            name=op.f("ck_operations_operation_state"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operations")),
        sa.UniqueConstraint(
            "operation_type",
            "idempotency_key",
            name="uq_operations_type_idempotency_key",
        ),
    )
    op.create_table(
        "agent_definitions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("display_name_pt", sa.String(length=200), nullable=True),
        sa.Column("system_prompt_id", sa.UUID(), nullable=True),
        sa.Column("model_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_definitions")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("actor_type", sa.String(length=50), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(op.f("ix_audit_logs_correlation_id"), "audit_logs", ["correlation_id"], unique=False)
    op.create_table(
        "backtest_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("strategy_name", sa.String(length=200), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("cagr_pct", sa.Float(), nullable=True),
        sa.Column("sharpe_ratio", sa.Float(), nullable=True),
        sa.Column("sortino_ratio", sa.Float(), nullable=True),
        sa.Column("calmar_ratio", sa.Float(), nullable=True),
        sa.Column("max_drawdown_pct", sa.Float(), nullable=True),
        sa.Column("win_rate_pct", sa.Float(), nullable=True),
        sa.Column("benchmark_name", sa.String(length=100), nullable=True),
        sa.Column("benchmark_cagr_pct", sa.Float(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backtest_results")),
    )
    op.create_table(
        "data_quality_checks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=True),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("check_name", sa.String(length=100), nullable=True),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_quality_checks")),
    )
    op.create_table(
        "data_refresh_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_name", sa.String(length=100), nullable=True),
        sa.Column("entity_type", sa.String(length=50), nullable=True),
        sa.Column("records_fetched", sa.Integer(), nullable=True),
        sa.Column("records_inserted", sa.Integer(), nullable=True),
        sa.Column("records_updated", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_refresh_log")),
    )
    op.create_table(
        "embeddings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("content_type", sa.String(length=50), nullable=True),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("text_snippet", sa.Text(), nullable=True),
        sa.Column("vector", Vector(1536), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_embeddings")),
    )
    op.create_index("ix_embeddings_entity_id", "embeddings", ["entity_id"], unique=False)
    op.create_table(
        "macro_indicators",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("indicator_name", sa.String(length=100), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.Column("period_date", sa.Date(), nullable=True),
        sa.Column("value", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("unit", sa.String(length=20), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_macro_indicators")),
    )
    op.create_index(op.f("ix_macro_indicators_period_date"), "macro_indicators", ["period_date"], unique=False)
    op.create_index(op.f("ix_macro_indicators_published_at"), "macro_indicators", ["published_at"], unique=False)
    op.create_table(
        "news_sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url_pattern", sa.Text(), nullable=True),
        sa.Column("trust_level", sa.Integer(), nullable=True),
        sa.Column("source_type", sa.String(length=20), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_news_sources")),
    )
    op.create_table(
        "portfolios",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_paper_trading", sa.Boolean(), nullable=True),
        sa.Column("base_currency", sa.String(length=3), nullable=True),
        sa.Column("initial_capital", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolios")),
    )
    op.create_table(
        "prompt_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("agent_name", sa.String(length=100), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=True),
        sa.Column("system_prompt", sa.Text(), nullable=True),
        sa.Column("instructions_pt", sa.Text(), nullable=True),
        sa.Column("structured_output_schema_id", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompt_versions")),
    )
    op.create_table(
        "sectors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name_pt", sa.String(length=100), nullable=False),
        sa.Column("name_en", sa.String(length=100), nullable=True),
        sa.Column("code_anbima", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sectors")),
    )
    op.create_table(
        "structured_output_schemas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=True),
        sa.Column("json_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_structured_output_schemas")),
    )
    op.create_table(
        "universe_filters",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("criteria", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_universe_filters")),
    )
    op.create_table(
        "workflow_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("temporal_workflow_id", sa.String(length=200), nullable=True),
        sa.Column("workflow_type", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_runs")),
    )
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("agent_definition_id", sa.UUID(), nullable=False),
        sa.Column("input_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("output_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("model_used", sa.String(length=100), nullable=True),
        sa.Column("tokens_prompt", sa.Integer(), nullable=True),
        sa.Column("tokens_completion", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_definition_id"],
            ["agent_definitions.id"],
            name=op.f("fk_agent_runs_agent_definition_id_agent_definitions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
    )
    op.create_table(
        "evaluation_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("agent_definition_id", sa.UUID(), nullable=True),
        sa.Column("evaluation_type", sa.String(length=50), nullable=True),
        sa.Column("metric_name", sa.String(length=100), nullable=True),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("dataset_id", sa.UUID(), nullable=True),
        sa.Column("model_version", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_definition_id"],
            ["agent_definitions.id"],
            name=op.f("fk_evaluation_results_agent_definition_id_agent_definitions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_results")),
    )
    op.create_table(
        "industries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name_pt", sa.String(length=100), nullable=False),
        sa.Column("name_en", sa.String(length=100), nullable=True),
        sa.Column("sector_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["sector_id"], ["sectors.id"], name=op.f("fk_industries_sector_id_sectors"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_industries")),
    )
    op.create_table(
        "news_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.Column("sentiment_score", sa.Float(), nullable=True),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_processed", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"], ["news_sources.id"], name=op.f("fk_news_items_source_id_news_sources"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_news_items")),
    )
    op.create_table(
        "portfolio_constraints",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("portfolio_id", sa.UUID(), nullable=False),
        sa.Column("constraint_type", sa.String(length=50), nullable=True),
        sa.Column("target", sa.String(length=100), nullable=True),
        sa.Column("limit_value", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_portfolio_constraints_portfolio_id_portfolios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_constraints")),
    )
    op.create_table(
        "rebalance_proposals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("portfolio_id", sa.UUID(), nullable=False),
        sa.Column("current_allocation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("proposed_allocation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("rationale_pt", sa.Text(), nullable=True),
        sa.Column("expected_return_change", sa.Float(), nullable=True),
        sa.Column("risk_impact", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_rebalance_proposals_portfolio_id_portfolios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rebalance_proposals")),
    )
    op.create_table(
        "risk_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("portfolio_id", sa.UUID(), nullable=False),
        sa.Column("snapshot_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_exposure", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("sector_concentration", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("top_risks", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("sharpe_ratio", sa.Float(), nullable=True),
        sa.Column("max_drawdown_pct", sa.Float(), nullable=True),
        sa.Column("volatility_annualized", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_risk_snapshots_portfolio_id_portfolios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_snapshots")),
    )
    op.create_table(
        "agent_tool_calls",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("agent_run_id", sa.UUID(), nullable=False),
        sa.Column("tool_name", sa.String(length=100), nullable=True),
        sa.Column("input_params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("output_result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_agent_tool_calls_agent_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_tool_calls")),
    )
    op.create_table(
        "approvals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("portfolio_id", sa.UUID(), nullable=True),
        sa.Column("rebalance_proposal_id", sa.UUID(), nullable=True),
        sa.Column("approver_name", sa.String(length=200), nullable=True),
        sa.Column("decision", sa.String(length=20), nullable=True),
        sa.Column("notes_pt", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["portfolio_id"], ["portfolios.id"], name=op.f("fk_approvals_portfolio_id_portfolios"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["rebalance_proposal_id"],
            ["rebalance_proposals.id"],
            name=op.f("fk_approvals_rebalance_proposal_id_rebalance_proposals"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
    )
    op.create_table(
        "issuers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name_pt", sa.String(length=200), nullable=False),
        sa.Column("cnpj", sa.String(length=14), nullable=True),
        sa.Column("cvm_code", sa.Integer(), nullable=True),
        sa.Column("industry_id", sa.UUID(), nullable=True),
        sa.Column("website_ri_url", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["industry_id"], ["industries.id"], name=op.f("fk_issuers_industry_id_industries"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_issuers")),
    )
    op.create_index(op.f("ix_issuers_cnpj"), "issuers", ["cnpj"], unique=True)
    op.create_index(op.f("ix_issuers_cvm_code"), "issuers", ["cvm_code"], unique=True)
    op.create_table(
        "proposed_trades",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("rebalance_proposal_id", sa.UUID(), nullable=False),
        sa.Column("ticker_symbol", sa.String(length=10), nullable=True),
        sa.Column("side", sa.String(length=10), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("target_price", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("rationale_pt", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["rebalance_proposal_id"],
            ["rebalance_proposals.id"],
            name=op.f("fk_proposed_trades_rebalance_proposal_id_rebalance_proposals"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proposed_trades")),
    )
    op.create_table(
        "agent_assessments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("agent_run_id", sa.UUID(), nullable=False),
        sa.Column("issuer_id", sa.UUID(), nullable=True),
        sa.Column("assessment_type", sa.String(length=50), nullable=True),
        sa.Column("verdict", sa.String(length=20), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("thesis_effect", sa.String(length=20), nullable=True),
        sa.Column("materiality_score", sa.Float(), nullable=True),
        sa.Column("time_horizon", sa.String(length=30), nullable=True),
        sa.Column("claims", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("risks", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("assumptions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("data_gaps", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("invalidation_triggers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_agent_assessments_agent_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["issuer_id"], ["issuers.id"], name=op.f("fk_agent_assessments_issuer_id_issuers"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_assessments")),
    )
    op.create_table(
        "detected_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("news_item_id", sa.UUID(), nullable=True),
        sa.Column("issuer_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(length=50), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("materiality_score", sa.Float(), nullable=True),
        sa.Column("direction_hint", sa.String(length=20), nullable=True),
        sa.Column("time_horizon", sa.String(length=20), nullable=True),
        sa.Column("affected_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("agent_run_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_detected_events_agent_run_id_agent_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["issuer_id"], ["issuers.id"], name=op.f("fk_detected_events_issuer_id_issuers"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["news_item_id"],
            ["news_items.id"],
            name=op.f("fk_detected_events_news_item_id_news_items"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_detected_events")),
    )
    op.create_table(
        "dividends",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("issuer_id", sa.UUID(), nullable=False),
        sa.Column("ticker_symbol", sa.String(length=10), nullable=True),
        sa.Column("dividend_type", sa.String(length=20), nullable=True),
        sa.Column("announcement_date", sa.Date(), nullable=True),
        sa.Column("ex_date", sa.Date(), nullable=True),
        sa.Column("payment_date", sa.Date(), nullable=True),
        sa.Column("amount_per_share", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("total_amount", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["issuer_id"], ["issuers.id"], name=op.f("fk_dividends_issuer_id_issuers"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dividends")),
    )
    op.create_index(op.f("ix_dividends_announcement_date"), "dividends", ["announcement_date"], unique=False)
    op.create_index(op.f("ix_dividends_ex_date"), "dividends", ["ex_date"], unique=False)
    op.create_table(
        "investment_theses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("issuer_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("summary_pt", sa.Text(), nullable=True),
        sa.Column("key_drivers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("risks", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("invalidation_criteria", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("review_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["issuer_id"], ["issuers.id"], name=op.f("fk_investment_theses_issuer_id_issuers"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_investment_theses")),
    )
    op.create_table(
        "news_entity_links",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("news_item_id", sa.UUID(), nullable=False),
        sa.Column("issuer_id", sa.UUID(), nullable=True),
        sa.Column("relevance_score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["issuer_id"], ["issuers.id"], name=op.f("fk_news_entity_links_issuer_id_issuers"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["news_item_id"],
            ["news_items.id"],
            name=op.f("fk_news_entity_links_news_item_id_news_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_news_entity_links")),
    )
    op.create_table(
        "positions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("portfolio_id", sa.UUID(), nullable=False),
        sa.Column("issuer_id", sa.UUID(), nullable=True),
        sa.Column("ticker_symbol", sa.String(length=10), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("avg_cost_per_share", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("current_price", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("weight_pct", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["issuer_id"], ["issuers.id"], name=op.f("fk_positions_issuer_id_issuers"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"], ["portfolios.id"], name=op.f("fk_positions_portfolio_id_portfolios"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_positions")),
    )
    op.create_table(
        "raw_documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("issuer_id", sa.UUID(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("document_type", sa.String(length=50), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=True),
        sa.Column("content_type", sa.String(length=100), nullable=True),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("sha256_hash", sa.String(length=64), nullable=True),
        sa.Column("http_etag", sa.Text(), nullable=True),
        sa.Column("http_last_modified", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reporting_period_start", sa.Date(), nullable=True),
        sa.Column("reporting_period_end", sa.Date(), nullable=True),
        sa.Column("parser_version", sa.String(length=50), nullable=True),
        sa.Column("license_policy", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["issuer_id"], ["issuers.id"], name=op.f("fk_raw_documents_issuer_id_issuers"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_documents")),
    )
    op.create_index(
        op.f("ix_raw_documents_reporting_period_end"), "raw_documents", ["reporting_period_end"], unique=False
    )
    op.create_index(
        op.f("ix_raw_documents_reporting_period_start"), "raw_documents", ["reporting_period_start"], unique=False
    )
    op.create_index(op.f("ix_raw_documents_sha256_hash"), "raw_documents", ["sha256_hash"], unique=False)
    op.create_table(
        "scorecards",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("issuer_id", sa.UUID(), nullable=False),
        sa.Column("scorecard_type", sa.String(length=50), nullable=True),
        sa.Column("as_of_date", sa.Date(), nullable=True),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column("growth_score", sa.Float(), nullable=True),
        sa.Column("leverage_score", sa.Float(), nullable=True),
        sa.Column("valuation_score", sa.Float(), nullable=True),
        sa.Column("overall_score", sa.Float(), nullable=True),
        sa.Column("veto_conditions_triggered", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["issuer_id"], ["issuers.id"], name=op.f("fk_scorecards_issuer_id_issuers"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scorecards")),
    )
    op.create_index(op.f("ix_scorecards_as_of_date"), "scorecards", ["as_of_date"], unique=False)
    op.create_table(
        "share_statistics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("issuer_id", sa.UUID(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=True),
        sa.Column("common_shares_outstanding", sa.BigInteger(), nullable=True),
        sa.Column("preferred_shares_a", sa.BigInteger(), nullable=True),
        sa.Column("preferred_shares_b", sa.BigInteger(), nullable=True),
        sa.Column("total_shares_outstanding", sa.BigInteger(), nullable=True),
        sa.Column("free_float_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["issuer_id"], ["issuers.id"], name=op.f("fk_share_statistics_issuer_id_issuers"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_share_statistics")),
    )
    op.create_index(op.f("ix_share_statistics_as_of_date"), "share_statistics", ["as_of_date"], unique=False)
    op.create_table(
        "tickers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("issuer_id", sa.UUID(), nullable=False),
        sa.Column("market_segment", sa.String(length=20), nullable=True),
        sa.Column("listing_date", sa.Date(), nullable=True),
        sa.Column("delisting_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["issuer_id"], ["issuers.id"], name=op.f("fk_tickers_issuer_id_issuers"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tickers")),
        sa.UniqueConstraint("symbol", "issuer_id", name=op.f("uq_tickers_symbol_issuer_id")),
    )
    op.create_index(op.f("ix_tickers_delisting_date"), "tickers", ["delisting_date"], unique=False)
    op.create_table(
        "universe_memberships",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("universe_filter_id", sa.UUID(), nullable=False),
        sa.Column("issuer_id", sa.UUID(), nullable=True),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["issuer_id"], ["issuers.id"], name=op.f("fk_universe_memberships_issuer_id_issuers"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["universe_filter_id"],
            ["universe_filters.id"],
            name=op.f("fk_universe_memberships_universe_filter_id_universe_filters"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_universe_memberships")),
    )
    op.create_table(
        "document_duplicates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("original_id", sa.UUID(), nullable=False),
        sa.Column("duplicate_id", sa.UUID(), nullable=False),
        sa.Column("similarity_method", sa.String(length=50), nullable=True),
        sa.Column("similarity_score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["duplicate_id"],
            ["raw_documents.id"],
            name=op.f("fk_document_duplicates_duplicate_id_raw_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["original_id"],
            ["raw_documents.id"],
            name=op.f("fk_document_duplicates_original_id_raw_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_duplicates")),
    )
    op.create_table(
        "document_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("raw_document_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["raw_document_id"],
            ["raw_documents.id"],
            name=op.f("fk_document_events_raw_document_id_raw_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_events")),
    )
    op.create_table(
        "document_metadata",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("raw_document_id", sa.UUID(), nullable=False),
        sa.Column("issuer_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.Column("parsed_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("extraction_errors", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_validated", sa.Boolean(), nullable=True),
        sa.Column("validation_notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["issuer_id"], ["issuers.id"], name=op.f("fk_document_metadata_issuer_id_issuers"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["raw_document_id"],
            ["raw_documents.id"],
            name=op.f("fk_document_metadata_raw_document_id_raw_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_metadata")),
    )
    op.create_table(
        "document_processing_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("raw_document_id", sa.UUID(), nullable=False),
        sa.Column("step_name", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["raw_document_id"],
            ["raw_documents.id"],
            name=op.f("fk_document_processing_log_raw_document_id_raw_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_processing_log")),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("raw_document_id", sa.UUID(), nullable=False),
        sa.Column("issuer_id", sa.UUID(), nullable=True),
        sa.Column("document_type", sa.String(length=50), nullable=True),
        sa.Column("reporting_period_start", sa.Date(), nullable=True),
        sa.Column("reporting_period_end", sa.Date(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("canonical_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["issuer_id"], ["issuers.id"], name=op.f("fk_documents_issuer_id_issuers"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["raw_document_id"],
            ["raw_documents.id"],
            name=op.f("fk_documents_raw_document_id_raw_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    op.create_table(
        "event_duplicates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("original_id", sa.UUID(), nullable=False),
        sa.Column("duplicate_id", sa.UUID(), nullable=False),
        sa.Column("similarity_method", sa.String(length=50), nullable=True),
        sa.Column("similarity_score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["duplicate_id"],
            ["detected_events.id"],
            name=op.f("fk_event_duplicates_duplicate_id_detected_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["original_id"],
            ["detected_events.id"],
            name=op.f("fk_event_duplicates_original_id_detected_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_duplicates")),
    )
    op.create_table(
        "event_impacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("thesis_id", sa.UUID(), nullable=True),
        sa.Column("impact_score", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("thesis_effect", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["detected_events.id"],
            name=op.f("fk_event_impacts_event_id_detected_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["thesis_id"],
            ["investment_theses.id"],
            name=op.f("fk_event_impacts_thesis_id_investment_theses"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_impacts")),
    )
    op.create_table(
        "evidence_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("assessment_id", sa.UUID(), nullable=False),
        sa.Column("claim_text", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("source_document_id", sa.UUID(), nullable=True),
        sa.Column("source_location", sa.Text(), nullable=True),
        sa.Column("metric_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["agent_assessments.id"],
            name=op.f("fk_evidence_items_assessment_id_agent_assessments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["raw_documents.id"],
            name=op.f("fk_evidence_items_source_document_id_raw_documents"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_items")),
    )
    op.create_table(
        "market_prices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ticker_id", sa.UUID(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("open_price", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("high_price", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("low_price", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("close_price", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=True),
        sa.Column("num_trades", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["ticker_id"], ["tickers.id"], name=op.f("fk_market_prices_ticker_id_tickers"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_prices")),
        sa.UniqueConstraint("ticker_id", "trade_date", name=op.f("uq_market_prices_ticker_id_trade_date")),
    )
    op.create_index(op.f("ix_market_prices_close_price"), "market_prices", ["close_price"], unique=False)
    op.create_index("ix_market_prices_ticker_id", "market_prices", ["ticker_id"], unique=False)
    op.create_table(
        "recommendations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("thesis_id", sa.UUID(), nullable=False),
        sa.Column("issuer_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=20), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("reasoning_pt", sa.Text(), nullable=True),
        sa.Column("supporting_assessments", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("opposing_arguments", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("review_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invalidation_triggers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["issuer_id"], ["issuers.id"], name=op.f("fk_recommendations_issuer_id_issuers"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["thesis_id"],
            ["investment_theses.id"],
            name=op.f("fk_recommendations_thesis_id_investment_theses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendations")),
    )
    op.create_table(
        "thesis_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("thesis_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=True),
        sa.Column("change_summary", sa.Text(), nullable=True),
        sa.Column("summary_pt", sa.Text(), nullable=True),
        sa.Column("key_drivers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("risks", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("invalidation_criteria", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("agent_run_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["thesis_id"],
            ["investment_theses.id"],
            name=op.f("fk_thesis_versions_thesis_id_investment_theses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_thesis_versions")),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("portfolio_id", sa.UUID(), nullable=False),
        sa.Column("position_id", sa.UUID(), nullable=True),
        sa.Column("side", sa.String(length=10), nullable=True),
        sa.Column("ticker_symbol", sa.String(length=10), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("price_per_share", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("execution_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_transactions_portfolio_id_portfolios"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["position_id"], ["positions.id"], name=op.f("fk_transactions_position_id_positions"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
    )
    op.create_index(op.f("ix_transactions_execution_date"), "transactions", ["execution_date"], unique=False)
    op.create_table(
        "execution_reconciliations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("transaction_id", sa.UUID(), nullable=True),
        sa.Column("broker_order_id", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("discrepancy_notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_execution_reconciliations_transaction_id_transactions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_execution_reconciliations")),
    )
    op.create_table(
        "financial_statements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("issuer_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("statement_type", sa.String(length=20), nullable=True),
        sa.Column("reporting_period_start", sa.Date(), nullable=False),
        sa.Column("reporting_period_end", sa.Date(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("currency_code", sa.String(length=3), nullable=True),
        sa.Column("scale_factor", sa.Integer(), nullable=True),
        sa.Column("line_items", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_audited", sa.Boolean(), nullable=True),
        sa.Column("restatement_flag", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_financial_statements_document_id_documents"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["issuer_id"], ["issuers.id"], name=op.f("fk_financial_statements_issuer_id_issuers"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_financial_statements")),
        sa.UniqueConstraint(
            "issuer_id",
            "statement_type",
            "reporting_period_end",
            name="uq_financial_statements_issuer_type_period",
        ),
    )
    op.create_index(
        op.f("ix_financial_statements_published_at"), "financial_statements", ["published_at"], unique=False
    )
    op.create_table(
        "financial_metrics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("issuer_id", sa.UUID(), nullable=False),
        sa.Column("reporting_period_end", sa.Date(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metric_name", sa.String(length=100), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("value", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("unit", sa.String(length=20), nullable=True),
        sa.Column("previous_value", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("change_absolute", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("change_percent", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("source_statement_id", sa.UUID(), nullable=True),
        sa.Column("calculation_method", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["issuer_id"], ["issuers.id"], name=op.f("fk_financial_metrics_issuer_id_issuers"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_statement_id"],
            ["financial_statements.id"],
            name=op.f("fk_financial_metrics_source_statement_id_financial_statements"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_financial_metrics")),
    )
    op.create_index(
        "ix_financial_metrics_issuer_metric_period",
        "financial_metrics",
        ["issuer_id", "metric_name", "reporting_period_end"],
        unique=False,
    )
    op.create_index(op.f("ix_financial_metrics_published_at"), "financial_metrics", ["published_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_financial_metrics_published_at"), table_name="financial_metrics")
    op.drop_index("ix_financial_metrics_issuer_metric_period", table_name="financial_metrics")
    op.drop_table("financial_metrics")
    op.drop_index(op.f("ix_financial_statements_published_at"), table_name="financial_statements")
    op.drop_table("financial_statements")
    op.drop_table("execution_reconciliations")
    op.drop_index(op.f("ix_transactions_execution_date"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_table("thesis_versions")
    op.drop_table("recommendations")
    op.drop_index("ix_market_prices_ticker_id", table_name="market_prices")
    op.drop_index(op.f("ix_market_prices_close_price"), table_name="market_prices")
    op.drop_table("market_prices")
    op.drop_table("evidence_items")
    op.drop_table("event_impacts")
    op.drop_table("event_duplicates")
    op.drop_table("documents")
    op.drop_table("document_processing_log")
    op.drop_table("document_metadata")
    op.drop_table("document_events")
    op.drop_table("document_duplicates")
    op.drop_table("universe_memberships")
    op.drop_index(op.f("ix_tickers_delisting_date"), table_name="tickers")
    op.drop_table("tickers")
    op.drop_index(op.f("ix_share_statistics_as_of_date"), table_name="share_statistics")
    op.drop_table("share_statistics")
    op.drop_index(op.f("ix_scorecards_as_of_date"), table_name="scorecards")
    op.drop_table("scorecards")
    op.drop_index(op.f("ix_raw_documents_sha256_hash"), table_name="raw_documents")
    op.drop_index(op.f("ix_raw_documents_reporting_period_start"), table_name="raw_documents")
    op.drop_index(op.f("ix_raw_documents_reporting_period_end"), table_name="raw_documents")
    op.drop_table("raw_documents")
    op.drop_table("positions")
    op.drop_table("news_entity_links")
    op.drop_table("investment_theses")
    op.drop_index(op.f("ix_dividends_ex_date"), table_name="dividends")
    op.drop_index(op.f("ix_dividends_announcement_date"), table_name="dividends")
    op.drop_table("dividends")
    op.drop_table("detected_events")
    op.drop_table("agent_assessments")
    op.drop_table("proposed_trades")
    op.drop_index(op.f("ix_issuers_cvm_code"), table_name="issuers")
    op.drop_index(op.f("ix_issuers_cnpj"), table_name="issuers")
    op.drop_table("issuers")
    op.drop_table("approvals")
    op.drop_table("agent_tool_calls")
    op.drop_table("risk_snapshots")
    op.drop_table("rebalance_proposals")
    op.drop_table("portfolio_constraints")
    op.drop_table("news_items")
    op.drop_table("industries")
    op.drop_table("evaluation_results")
    op.drop_table("agent_runs")
    op.drop_table("workflow_runs")
    op.drop_table("universe_filters")
    op.drop_table("structured_output_schemas")
    op.drop_table("sectors")
    op.drop_table("prompt_versions")
    op.drop_table("portfolios")
    op.drop_table("news_sources")
    op.drop_index(op.f("ix_macro_indicators_published_at"), table_name="macro_indicators")
    op.drop_index(op.f("ix_macro_indicators_period_date"), table_name="macro_indicators")
    op.drop_table("macro_indicators")
    op.drop_index("ix_embeddings_entity_id", table_name="embeddings")
    op.drop_table("embeddings")
    op.drop_table("data_refresh_log")
    op.drop_table("data_quality_checks")
    op.drop_table("backtest_results")
    op.drop_table("audit_logs")
    op.drop_table("agent_definitions")
    op.drop_table("operations")
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS vector")
