"""CVM account code mappings and description pattern lookups."""

from __future__ import annotations

CVM_ACCOUNT_MAP: dict[str, str] = {
    "1.01": "caixa",
    "1.01.01": "caixa",
    "1.01.02": "aplicacoes_financeiras",
    "1.02": "contas_receber",
    "1.02.01": "contas_receber",
    "1.02.02": "estoques",
    "1.02.03": "ativos_biologicos",
    "1.03": "tributos_a_receber",
    "1.04": "adiantamentos",
    "1.05": "ativos_nao_correntes_manutencao",
    "2.01": "investimentos",
    "2.02": "imobilizado",
    "2.03": "intangiveis",
    "2.04": "diferido",
    "2.05": "ativos_ambientais",
    "3.01": "fornecedores",
    "3.02": "emprestimos_circulantes",
    "3.02.01": "divida_bancaria_circulante",
    "3.03": "obrigacoes_fiscais",
    "3.04": "obrigacoes_trabalhistas",
    "3.05": "dividendos_a_pagar",
    "3.06": "adiantamentos_clientes",
    "3.07": "outros_passivos_circulantes",
    "4.01": "emprestimos_nao_circulantes",
    "4.01.01": "divida_bancaria_nao_circulante",
    "4.02": "debentures",
    "4.03": "obrigacoes_afetadas",
    "4.04": "provisoes",
    "4.05": "passivos_ambientais",
    "4.06": "outros_passivos_nao_circulantes",
    "5.01": "capital_social",
    "5.02": "reservas",
    "5.03": "lucros_acumulados",
    "5.04": "resultados_nao_apropriados",
    "5.05": "ajustes_avaliacao",
    "5.06": "outros",
    "6.01": "receita_liquida",
    "6.02": "receita_bruta",
    "6.02.01": "impostos_sobre_receita",
    "6.03": "custo_receita",
    "7.01": "lucro_bruto",
    "8.01": "despesas_vendas",
    "8.02": "despesas_administrativas",
    "8.03": "despesas_financeiras",
    "8.03.01": "receitas_financeiras",
    "8.03.02": "despesas_financeiras_brutas",
    "8.04": "outras_receitas_operacionais",
    "8.05": "outras_despesas_operacionais",
    "9.01": "lucro_operacional_anteriores",
    "9.02": "resultados_nao_operacionais",
    "10.01": "lucro_before_tax",
    "10.02": "imposto_renda",
    "10.03": "contribuicao_social",
    "11.01": "lucro_liquido",
    "12.01": "ebit",
    "12.02": "depreciacao_amortizacao",
    "12.03": "ebitda",
}

_DESCRIPTION_PATTERNS: dict[str, list[str]] = {
    "caixa": ["caixa e equivalentes de caixa", "caixa e equiv"],
    "aplicacoes_financeiras": ["aplicações financeiras", "aplicacoes financeiras", "títulos"],
    "contas_receber": ["contas a receber", "clientes", "tributos a recuperar"],
    "estoques": ["estoques", "estoque"],
    "ativos_biologicos": ["ativos biológicos"],
    "investimentos": ["investimentos"],
    "imobilizado": ["imobilizado", "imóveis", "propriedades"],
    "intangiveis": ["intangíveis", "intangiveis"],
    "divididos": ["dívida de arrendamento", "divida de arrendamento"],
    "divida_bancaria_circulante": ["empréstimos", "empréstimos bancários", "financiamentos"],
    "divida_bancaria_nao_circulante": ["empréstimos a longo prazo", "financiamentos a longo"],
    "fornecedores": ["fornecedores"],
    "obrigacoes_fiscais": ["impostos a recolher", "tributos a pagar", "obrigações tributárias"],
    "capital_social": ["capital social", "capital emitido"],
    "reservas": ["reservas de lucros", "reservas de capital"],
    "lucros_acumulados": ["lucros ou prejuízos acumulados"],
    "ajustes_avaliacao": ["ajustes de avaliação patrimonial"],
    "receita_liquida": ["receita líquida", "receita liquida"],
    "receita_bruta": ["receita bruta"],
    "impostos_sobre_receita": ["impostos sobre a receita", "contribuições"],
    "custo_receita": ["custo dos bens e serviços vendidos", "custo da receita"],
    "lucro_bruto": ["lucro bruto"],
    "despesas_vendas": ["despesas com vendas"],
    "despesas_administrativas": ["despesas administrativas"],
    "despesas_financeiras": ["despesas financeiras"],
    "receitas_financeiras": ["receitas financeiras"],
    "outras_receitas_operacionais": ["outras receitas operacionais"],
    "outras_despesas_operacionais": ["outras despesas operacionais"],
    "resultados_nao_operacionais": ["resultados não operacionais"],
    "lucro_before_tax": ["lucro antes do irpj e csll"],
    "imposto_renda": ["imposto de renda"],
    "contribuicao_social": ["contribuição social"],
    "lucro_liquido": ["lucro/prejuízo líquido", "lucro liquido", "prejuízo líquido"],
    "ebit": ["lucro antes dos juros e impostos", "lucro operacional antes"],
    "depreciacao_amortizacao": ["depreciação e amortização", "depreciação", "amortização"],
    "ebitda": ["ebitda"],
}
